### PR TITLE
[0.15.x] Fix trusty ui script backport

### PR DESCRIPTION
**Pull request by r00ta**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by Kaitou786 — APPROVED** [review]

**Comment by spolti** [comment]
should this imagestream commit be here as well?

**Comment by r00ta** [comment]
Hi @spolti , the imagestream fix was merged after the branch 0.15 was created. I think we should have it updated as well since now the trusty-ui and explainability images are there. If you prefer to keep it out from 0.15 I'll remove it

**Comment by spolti** [comment]
It's ok for me but is trusty work to be available on 0.15?
@ricardozanini, @sutaakar ?

**Comment by ricardozanini** [comment]
it will

**Pull request merged**
