### PR TITLE
[kie-issues@1167] Add license headers to files

### LINKED ISSUE #1167: incubator-kie-kogito-images files needing license headers
https://gist.github.com/LightGuard/3db0816744545edf907ae49e6a6df7bd

The following kinds of files need to be updated to include the ASL license header:

* Makefile
* Markdown
* Dockerfiles
* Significant text files

### PR DESCRIPTION
**Pull request by baldimir**
Resolves https://github.com/apache/incubator-kie-issues/issues/1167

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **ABORTED**
Possible explanation: Most probably a timeout, please review

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/2/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Build KIE » kogito » main » pullrequest » kogito-images.build-image #1 completed: ABORTED<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #7 completed: ABORTED<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-allinone<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-postgresql<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #2 completed: ABORTED<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #6 completed: ABORTED<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jit-runner<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-ephemeral<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #5 completed: ABORTED<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-postgresql<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #3 completed: ABORTED<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #4 completed: ABORTED<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-base-builder<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-ephemeral<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/2/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by yesamer — APPROVED** [review]

**Review by porcelli — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/3/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Starting building: KIE » kogito » main » pullrequest » kogito-images.build-image #9<br/>Starting building: KIE » kogito » main » pullrequest » kogito-images.build-image #11<br/>Starting building: KIE » kogito » main » pullrequest » kogito-images.build-image #13<br/>Starting building: KIE » kogito » main » pullrequest » kogito-images.build-image #10<br/>Starting building: KIE » kogito » main » pullrequest » kogito-images.build-image #14<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-base-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/3/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/4/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Starting building: KIE » kogito » main » pullrequest » kogito-images.build-image #15<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-base-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-data-index-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1763 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1763 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-allinone seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/4/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by baldimir** [comment]
Hi @ricardozanini, do you have a hint please what could be the problem with the Jenkins check?

**Comment by ricardozanini** [comment]
@baldimir know issues with our underlying tool for testing: https://github.com/cekit/behave-test-steps/issues/68

**Comment by ricardozanini** [comment]
Please add me as a reviewer for these PRs since I'm maintaining this repo.

**Review by ricardozanini — APPROVED** [review]

**Comment by baldimir** [comment]
Thank you, yes I forgot to click you. Sorry for that.

**Pull request merged**
