### PR TITLE
Issue #1747 - Remove Kogito Operator managed images

### LINKED ISSUE #1747: Remove images managed by the Kogito Operator
As part of the process for archiving the Kogito Operator, we must remove a few images in this repo:

- [kogito-base-builder](https://github.com/apache/incubator-kie-kogito-images/blob/1.44.2.x/kogito-base-builder-image.yaml)
- [kogito-runtime-jvm](https://github.com/apache/incubator-kie-kogito-images/blob/1.44.2.x/kogito-runtime-jvm-image.yaml)
- [kogito-runtime-native](https://github.com/apache/incubator-kie-kogito-images/blob/1.44.2.x/kogito-runtime-native-image.yaml)
- [kogito-s2i-builder](https://github.com/apache/incubator-kie-kogito-images/blob/1.44.2.x/kogito-s2i-builder-image.yaml)

See more info: 

- https://github.com/apache/incubator-kie-kogito-operator/issues/1537

### PR DESCRIPTION
**Pull request by ricardozanini**
Many thanks for submitting your Pull Request :heart:! 

Closes #1747 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#107` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/107/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-ephemeral<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-allinone<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-management-console: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-management-console<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-task-console<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-builder<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/107/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#108` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/108/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-ephemeral<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jit-runner<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-ephemeral<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-builder<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-postgresql<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/108/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by porcelli — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#109` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/109/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-management-console: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-allinone seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-postgresql seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/109/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
Failures duo to the renaming. I'm going to rename the extensions in the images before attempting to merge this one.

**Comment by ricardozanini** [comment]
Depends on #1749

**Review by wmedvede — APPROVED** [review]

**Comment by ricardozanini** [comment]
@porcelli @wmedvede once green we can merge this one too since the artifacts renaming has been merged.

**Comment by kie-ci3** [comment]
**PR job** `#134` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/134/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-data-index-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-management-console: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1748 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1748 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/134/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by domhanak — APPROVED** [review]

**Comment by ricardozanini** [comment]
One flacky test that was already reported, is not related. We are safe to merge and remove unneeded images. @jakubschwan wanna take a final look?

**Pull request merged**
