### PR TITLE
build-quarkus-app.sh: allow to copy local deployed artifacts when running as part of nightly

### PR DESCRIPTION
**Pull request by rgdoliveira**
`build-quarkus-app.sh` script uses `-Dmaven.repo.local` and points to a clean folder, so the Kogito artifacts built as part of the nightly (that are not deployed anywhere yet) can't be found.

This PR allows, in case of a nightly, to copy the Kogito/Drools artifacts deployed locally to the same path that `-Dmaven.repo.local` points, so the artifacts can be resolved.

…

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>

- <b>Prod tests</b>  
  Please add comment: <b>Jenkins (re)run [prod|Prod|PROD]</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by kie-ci1** [comment]
**PR job** `#845` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/845/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[INFO] Cleaning up running containers and images. Any error here can be ignored<br/>[Pipeline] sh<br/>+ docker ps -a -q<br/>+ tr '\n' ,<br/>[Pipeline] sh<br/>+ docker images -q<br/>+ tr '\n' ,<br/>[Pipeline] sh<br/>+ docker buildx rm mybuilder<br/>ERROR: no builder "mybuilder" found<br/>+ true<br/>[Pipeline] sh<br/>+ docker rm -f binfmt<br/>Error response from daemon: No such container: binfmt<br/>[Pipeline] sh<br/>+ docker context ls<br/>NAME        DESCRIPTION                               DOCKER ENDPOINT               ERROR<br/>default *   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock   <br/>[Pipeline] sh<br/>+ docker buildx inspect<br/>Name:   default<br/>Driver: docker<br/><br/>Nodes:<br/>Name:      default<br/>Endpoint:  default<br/>Status:    running<br/>Buildkit:  v0.11.7-0.20230525183624-798ad6b0ce9f<br/>Platforms: linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386<br/>[Pipeline] sh<br/>+ docker buildx ls<br/>NAME/NODE DRIVER/ENDPOINT STATUS  BUILDKIT                              PLATFORMS<br/>default * docker                                                        <br/>  default default         running v0.11.7-0.20230525183624-798ad6b0ce9f linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386<br/>[Pipeline] sh<br/>+ docker rm -f registry-5000<br/>Error response from daemon: No such container: registry-5000<br/>[Pipeline] sh<br/>+ docker ps<br/>CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/845/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by radtriste — APPROVED** [review]

**Comment by kie-ci1** [comment]
**PR job** `#846` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/846/display/redirect

**Test results:**
- PASSED: 269
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/846/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Perform_a_second_incremental_s2i_build_for_native_scenario,_this_time,_with_native_enabled/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Perform a second incremental s2i build for native scenario, this time, with native enabled</a></summary>
Phrase 'Expanding artifacts from incremental build...' was not found in the output of S2I
</details>

**Comment by rgdoliveira** [comment]
jenkins retest this

**Review by lampajr — APPROVED** [review]

**Comment by kie-ci1** [comment]
**PR job** `#850` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/850/display/redirect

**Test results:**
- PASSED: 269
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/850/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Perform_a_second_incremental_s2i_build_for_native_scenario,_this_time,_with_native_enabled/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Perform a second incremental s2i build for native scenario, this time, with native enabled</a></summary>
Phrase 'Expanding artifacts from incremental build...' was not found in the output of S2I
</details>

**Comment by kie-ci1** [comment]
**PR job** `#849` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/849/display/redirect

**Test results:**
- PASSED: 268
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/849/testReport/features.image.kogito-common-builder-jvm/kogito-s2i-builder image JVM build tests/Perform_a_second_incremental_s2i_build_using_quarkus_runtime_type/">features.image.kogito-common-builder-jvm.kogito-s2i-builder image JVM build tests.Perform a second incremental s2i build using quarkus runtime type</a></summary>
Phrase 'Expanding artifacts from incremental build...' was not found in the output of S2I
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/849/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Perform_a_second_incremental_s2i_build_for_native_scenario,_this_time,_with_native_enabled/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Perform a second incremental s2i build for native scenario, this time, with native enabled</a></summary>
Phrase 'Expanding artifacts from incremental build...' was not found in the output of S2I
</details>

**Comment by rgdoliveira** [comment]
Backport PR https://github.com/kiegroup/kogito-images/pull/1577 merged in branch `1.40.x`

**Pull request merged**
