### PR TITLE
[KOGITO-1945] Release Kogito Images 0.10.0

### PR DESCRIPTION
**Pull request by radtriste**
staging data-index: data-index-service-0.10.0-runner.jar
md5: 989299a600c47695153f791cc9acdb14

staging jobs-service: jobs-service-0.10.0-runner.jar
md5: 71619ecd10e9ff63b47e2c6af8081488

staging management-console: management-console-0.10.0-runner.jar
md5: b46184831948061b64fbe37e0c158400

images to be available in a few hours on quay.io under tag 0.10.0-rc2:
- quay.io/kiegroup/kogito-data-index:0.10.0-rc2
- quay.io/kiegroup/kogito-jobs-service:0.10.0-rc2
- quay.io/kiegroup/kogito-management-console:0.10.0-rc2
- quay.io/kiegroup/kogito-quarkus-jvm-ubi8:0.10.0-rc2
- quay.io/kiegroup/kogito-quarkus-ubi8:0.10.0-rc2
- quay.io/kiegroup/kogito-quarkus-ubi8-s2i:0.10.0-rc2
- quay.io/kiegroup/kogito-springboot-ubi8:0.10.0-rc2
- quay.io/kiegroup/kogito-springboot-ubi8-s2i:0.10.0-rc2

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Comment by spolti** [comment]
You might need to update the tests as well, there is a new tag on kogito examples, we probably need to use that.

**Comment by radtriste** [comment]
oh ok.
You mean 0.10.0 tags ?

**Comment by spolti** [comment]
yes

**Comment by spolti** [comment]
depends on https://github.com/kiegroup/kogito-images/pull/147

**Review by MarianMacik — APPROVED** [review]

**Comment by spolti** [comment]
@radtriste can you please rebase?

**Comment by radtriste** [comment]
rebase done
set version to 0.10

**Review by spolti — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Pull request merged**
