### PR TITLE
[KOGITO-5138] - Using latest ubi8 image for all Kogito images

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-5138

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by spolti — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
network issue ...

Jenkins retest this

**Review by vaibhavjainwiz — APPROVED** [review]

**Comment by radtriste** [comment]
and again ...
```
Docker: + rpm -i https://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

2021-05-19 03:06:06,064 docker_builder.py:108        INFO  Docker: curl: (22) The requested URL returned error: 404

2021-05-19 03:06:06,065 docker_builder.py:108        INFO  Docker: error: skipping https://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm - transfer failed
```

Jenkins retest this

**Comment by radtriste** [comment]
https://github.com/kiegroup/kogito-examples/commit/8b4a725b12cb8dfac81c1246021663dd1525ad8c has been merged yesterday and new artifacts are not yet on Maven repository

**Comment by ricardozanini** [comment]
> [kiegroup/kogito-examples@8b4a725](https://github.com/kiegroup/kogito-examples/commit/8b4a725b12cb8dfac81c1246021663dd1525ad8c) has been merged yesterday and new artifacts are not yet on Maven repository

Do you think we can merge this either way? It's blocking other PRs and the CI. Or it's ok to wait one more day? (We also need to cherry-pick this one on 1.7.x).

**Comment by radtriste** [comment]
https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/kogito/job/nightly/job/master/job/kogito-examples-deploy/ is almost finished :D let's wait some more minutes ;)

**Comment by spolti** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
still network issues ... 
Jenkins retest this

**Comment by ricardozanini** [comment]
Jenkins retest this

**Comment by ricardozanini** [comment]
Jenkins retest this

**Comment by spolti** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
failing test will be corrected with https://github.com/kiegroup/kogito-apps/pull/827
we can now merge :)

**Pull request merged**
