### PR TITLE
[KOGITO-1336] - Improve the exposed HTTP port configuration for Kogit…

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
…o Runtime Services
Jira issue : https://issues.redhat.com/browse/KOGITO-1336
depends on : https://github.com/kiegroup/kogito-cloud-operator/pull/378

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
LGTM

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
let's wait CI report success.

**Review by sutaakar — APPROVED** [review]

**Review by radtriste — APPROVED** [review]
lgtm

**Comment by ricardozanini** [comment]
@spolti please wait for the changes in https://github.com/kiegroup/kogito-cloud-operator/pull/378

**Comment by spolti** [comment]
@vaibhavjainwiz can you please check the tests? seems to be related with your changes;

**Comment by vaibhavjainwiz** [comment]
> @vaibhavjainwiz can you please check the tests? seems to be related with your changes;

@spolti Issue has been fixed now

**Comment by Kaitou786** [comment]
Jenkins, retest this please

**Pull request merged**
