### PR TITLE
[KOGITO-1934] - Add a flag on the push-staging.py script to allow-ove…

### PR DESCRIPTION
**Pull request by spolti**
…rride rc images

Signed-off-by: spolti <fspolti@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Kaitou786** [comment]
Jenkins test this

**Comment by radtriste** [comment]
With nightly images and release pipeline, do we still need that script ?

**Review by vaibhavjainwiz — APPROVED** [review]
LGTM

**Review by sutaakar — APPROVED** [review]

**Review by Kaitou786 — APPROVED** [review]

**Comment by spolti** [comment]
CI is complaining about:
```
Error: Class initialization of io.quarkus.runner.ApplicationImpl failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl to explicitly request delayed initialization of this class.

Original exception that caused the problem: java.lang.NoClassDefFoundError: io/quarkus/runtime/util/StepTiming

```
quarkus version mismatch in the kogito examples?

**Review by radtriste — APPROVED** [review]

**Comment by spolti** [comment]
Jenkins retest this

**Pull request merged**
