### PR TITLE
Added support to run the non-native application directly from the S2I…

### PR DESCRIPTION
**Pull request by DuncanDoyle**
… image. Requires the runtime environment flag NATIVE=false (same as the assemble part).

### CODE REVIEW

**Comment by ricardozanini** [comment]
@DuncanDoyle many thanks for your PR. Have you tested with [`cekit`](https://docs.cekit.io/en/latest/handbook/testing/behave.html) this change?

**Comment by ricardozanini** [comment]
@DuncanDoyle the CI is failing to clone your repo:

```
Cloning the remote Git repository
Cloning repository https://github.com/DuncanDoyle/kogito-cloud.git
 > git init /home/jenkins/workspace/KIE/master/kogito-deploy/kogito-cloud-s2i-images-master/kogito-cloud # timeout=10
Fetching upstream changes from https://github.com/DuncanDoyle/kogito-cloud.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/DuncanDoyle/kogito-cloud.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/DuncanDoyle/kogito-cloud.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/DuncanDoyle/kogito-cloud.git/'
```

Just wondering if you have any configuration that is preventing Jenkins from cloning your repo.

Tried locally and also failed:

```
 git clone https://github.com/DuncanDoyle/kogito-cloud.git
Cloning into 'kogito-cloud'...
Username for 'https://github.com': ricardozanini
Password for 'https://ricardozanini@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/DuncanDoyle/kogito-cloud.git/'
```

Could you please review? Please also note the above comment regarding the behave tests.

Thanks!

**Review by ricardozanini — CHANGES_REQUESTED** [review]
Please see comments above.

**Comment by spolti** [comment]
This functionality will be implemented as part of [KOGITO-515](https://issues.jboss.org/browse/KOGITO-515)

**Pull request closed without merging**
