### PR TITLE
[KOGITO-3482] - Remove handling of runtime configuration from kogtio …

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
…images

Jira Issue : https://issues.redhat.com/browse/KOGITO-3482

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by sutaakar** [comment]
Configuration can be passed using env variable (i.e. `-e KOGITO_JOBS_SERVICE_MAXINTERVALLIMITTORETRYMILLIS=10000`)

**Review by Kaitou786 — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@spolti whenever you want.

**Comment by spolti** [comment]
@sutaakar I didnt find it on the docs, but I suppose it is using the ConfigProperty on the jobs service side, right?
@sterobin should we document this on how user can use envs on images as @sutaakar pointed out above?

**Review by spolti — APPROVED** [review]

**Comment by sutaakar** [comment]
@spolti Right, it is a ConfigProperty - https://github.com/kiegroup/kogito-apps/blob/master/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/impl/TimerDelegateJobScheduler.java#L63-L66

**Comment by spolti** [comment]
@sutaakar thanks for the confirmation.
Then, maybe only point somewhere in the docs that the properties can be set using env with the same name then properties.

**Comment by ricardozanini** [comment]
> @sutaakar thanks for the confirmation.
> Then, maybe only point somewhere in the docs that the properties can be set using env with the same name then properties.

I believe I pointed this out in some PR out there. Here's the Quarkus doc:
https://quarkus.io/guides/config#overriding-properties-at-runtime

This should be mentioned in our docs.

**Comment by spolti** [comment]
@vaibhavjainwiz can you please get in touch with @sterobin to add it do the docs?

**Comment by vaibhavjainwiz** [comment]
> @vaibhavjainwiz can you please get in touch with @sterobin to add it do the docs?

sure @spolti , Actually this PR is just a small task to implement KOGITO-3273. I already have kie-doc update subtask in my bucket https://issues.redhat.com/browse/KOGITO-3483. We are planning to update docs onces KOGITO-3273 implementation will complete

**Comment by spolti** [comment]
@vaibhavjainwiz ok, thanks, added a note on the jira :)

**Pull request merged**
