### PR TITLE
[KOGITO-2912][KOGITO-2855][KOGITO-2946] Cherry-picking scripts change for future 0.13.1 release

### PR DESCRIPTION
**Pull request by radtriste**
Depends on https://github.com/kiegroup/kogito-images/pull/203 due to Quarkus 1.7 change in runtimes

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins test this

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Merging as this PR and https://github.com/kiegroup/kogito-images/pull/203 are deadlocking ...

**Pull request merged**
