### PR TITLE
KOGITO-1355 - Update slave label for jenkins build

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mbiarnes @spolti @ricardozanini _kogito-cloud-s2i-images-master_ build is not there( in jenkins ), should we remove this step?

**Comment by spolti** [comment]
No, it doesn't, looks like the job was removed from jenkins, do you know why it was removed?

**Comment by cristianonicolai** [comment]
@mbiarnes seems like we missed this job from the kogito scripts: https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/jobs/kogito.groovy#L312

**Comment by spolti** [comment]
@mbiarnes updates?

**Comment by spolti** [comment]
Plus, this node needs to have cekit and its dependencies/configurations in place.

**Comment by spolti** [comment]
@cristianonicolai apparently we'll not need it anymore, can we close this PR?

**Pull request closed without merging**
