### PR TITLE
[kie-issues#963] Remove all references to kogito-task-console and kogito-management-console

### LINKED ISSUE #963: Move `task-console` and `management-console` images from `kogito-images` to `kie-tools`
We can create two new packages, `packages/task-console-image` and `packages/management-console-image`. We can use Dockerfiles and copy the strategy we have for `packages/kie-sandbox-image`.

### PR DESCRIPTION
**Pull request by thiagoelg**
Closes https://github.com/apache/incubator-kie-issues/issues/963

This PR removes all references to `kogito-task-console` and `kogito-management-console` images, as they are being migrated to kie-tools [1].
It also fixes a small bug in the Makefile that prevented the `make` command from building all images.

[1] https://github.com/apache/incubator-kie-tools/pull/2226

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
Are you going to still use the same architecture (Cekit) when moving those to kie-tools?

**Comment by thiagoelg** [comment]
> Are you going to still use the same architecture (Cekit) when moving those to kie-tools?

No, we are using kie-tools tooling (image-builder [1]) to build the image now. Also, it's not a Java-based image anymore, we figured out it's enough to have Apache httpd serve the static webapp files and provide a way to change environment variables (to set the data index endpoint, for example).

If we're missing something or not meeting a requirement, let us know.

[1] https://github.com/apache/incubator-kie-tools/tree/main/packages/image-builder

**Comment by kie-ci3** [comment]
**PR job** `#137` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/137/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-runtime-native: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-runtime-native<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-s2i-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/137/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by tiagobento** [comment]
@ricardozanini For the temporary copies of `kogito-swf-{devmode,builder}` we intend to keep the same build tools, though... and we'll most likely need your assistance :)

**Comment by ricardozanini** [comment]
@tiagobento count on me

**Comment by ricardozanini** [comment]
@thiagoelg please rebase, we've removed unused images and this PR might be simpler now :)

**Comment by thiagoelg** [comment]
@ricardozanini I'm not sure why ShellCheck is failing, do you have any ideas?

**Comment by ricardozanini** [comment]
Try looking for this `openBinaryFile` method. Maybe it was a script used in the modules you're removing.

**Comment by kie-ci3** [comment]
**PR job** `#143` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/143/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-data-index-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-allinone seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-builder seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-devmode seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/143/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by thiagoelg** [comment]
@ricardozanini Apparently, ShellCheck never worked (or I'm missing something), because Bash didn't work well with globstar. After I enabled it ShellCheck started printing a bunch of warnings and infos regarding the scripts.

I could add a `-S error` to the ShellCheck command so it only alerts for Error cases, but I can't fix the warnings and infos as I don't have the proper context of these scripts.

**Comment by kie-ci3** [comment]
**PR job** `#144` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/144/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-builder seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-devmode seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/144/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#145` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/145/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-builder seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/145/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
@thiagoelg please remove the globstar, this action has been working on all the other PRs. I'll take a look after you revert it.

**Comment by ricardozanini** [comment]
@thiagoelg I think I've found the problem, I'll send a PR later to solve this.

**Comment by ricardozanini** [comment]
Fixed here: https://github.com/apache/incubator-kie-kogito-images/pull/1756

Once I get green, we can merge, rebase here and we should be good to go.

**Comment by thiagoelg** [comment]
Awesome! Thanks @ricardozanini

**Comment by kie-ci3** [comment]
**PR job** `#147` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/147/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-allinone seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-builder seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-devmode seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/147/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#153` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/153/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-data-index-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-builder seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-devmode seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/153/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
The images build are broken, please see: https://github.com/apache/incubator-kie-kogito-runtimes/issues/3473

**Comment by kie-ci3** [comment]
**PR job** `#154` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/154/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-builder seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/154/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#155` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/155/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-data-index-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-allinone seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1753 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1753 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/155/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by pefernan — APPROVED** [review]

**Comment by ricardozanini** [comment]
Failed tests not related, still issues from cekit/infra.

**Comment by tiagobento** [comment]
@ricardozanini What is missing for us to be able to merge this?

**Comment by kie-ci3** [comment]
**PR job** `#159` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/159/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/thiagoelg/incubator-kie-kogito-images<br/> * branch              kie-issues-963 -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/thiagoelg/incubator-kie-kogito-images kie-issues-963<br/>        Target: af98d962 Temporary removal of kogito-swf-{builder-,devmode} images from release pipelines (#1752)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/159/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
> @ricardozanini What is missing for us to be able to merge this?

You already have my approval review (which I made last week) and a comment saying that the tests are not related. It could have been merged already.

I'm merging since I'm assuming it's alright from your side too.

**Pull request merged**
