### PR TITLE
[KOGITO-5623] Fix Behave tests for SW builder

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See https://issues.redhat.com/browse/KOGITO-5623

This PR fixes the error in the SW behave test. We were missing the `datacontenttype` attribute in the CE payload.

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by vaibhavjainwiz — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins retest this

**Comment by ricardozanini** [comment]
jenkins retest this

**Comment by spolti** [comment]
Issue:

```
Failed to execute goal io.quarkus:quarkus-maven-plugin:2.1.0.Final:add-extension (default-cli) on project myproject: Failed to initialize Quarkus Maven extension manager: Failed to resolve Quarkus extension registry descriptor io.quarkus.registry:quarkus-registry-descriptor:json:1.0-SNAPSHOT from mirror.default (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/) -> [Help 1]
```

**Comment by ricardozanini** [comment]
@spolti, we are missing the dependency on our mirror if I could understand it correctly.

**Comment by ricardozanini** [comment]
@spolti see https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/quarkus-registry-descriptor.20maven.20dependency.20not.20found

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by ricardozanini** [comment]
@radtriste, there's no drawback disabling their registry?

**Comment by radtriste** [comment]
this was on Quarkus team advice, gonna ask

**Comment by radtriste** [comment]
failed on another test ... adding a comment and restarting

**Comment by radtriste** [comment]
@ricardozanini 
```
The only drawback is that you won't get any Quarkiverse extension versions when running add-extension to your project, which doesn't seem to be the case I guess
```

**Comment by ricardozanini** [comment]
It's failing in the groovy script. I'll take a look.

```
ERROR:root:I0805 12:46:43.227505    5169 sti.go:711] [INFO] Executing META-INF/archetype-post-generate.groovy post-generation script
ERROR:root:I0805 12:46:43.710320    5169 sti.go:711] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: startup failed:
ERROR:root:I0805 12:46:43.710371    5169 sti.go:711] [ERROR] Script1.groovy: 45: Ambiguous expression could be either a parameterless closure expression or an isolated open code block;
ERROR:root:I0805 12:46:43.710429    5169 sti.go:711] [ERROR]    solution: Add an explicit closure parameter list, e.g. {it -> ...}, or force it to be treated as an open block by giving it a label, e.g. L:{...} @ line 45, column 9.
ERROR:root:I0805 12:46:43.711725    5169 sti.go:711] [ERROR]            {
ERROR:root:I0805 12:46:43.711756    5169 sti.go:711] [ERROR]            ^
ERROR:root:I0805 12:46:43.711764    5169 sti.go:711] [ERROR]
ERROR:root:I0805 12:46:43.711769    5169 sti.go:711] [ERROR] 1 error
ERROR:root:I0805 12:46:43.711776    5169 sti.go:711] [ERROR] -> [Help 1]
```

**Comment by ricardozanini** [comment]
Fixed in:
https://github.com/kiegroup/kogito-runtimes/pull/1508

**Comment by radtriste** [comment]
if we are good with that one, we would need to cherry-pick to 1.10.x

**Comment by ricardozanini** [comment]
I think we won't need since it didn't make the cut.

**Comment by radtriste** [comment]
> I think we won't need since it didn't make the cut.

The registry error is in the tests ;) So we need at least to add the registry disabling.

**Comment by radtriste** [comment]
Fix for 1.10.x: https://github.com/kiegroup/kogito-images/pull/650

**Comment by ricardozanini** [comment]
> > I think we won't need since it didn't make the cut.
> 
> The registry error is in the tests ;) So we need at least to add the registry disabling.

my bad! I thought you were referring to the runtime fix. Sure.

**Comment by spolti** [comment]
there is a new issue?
now this one is failing
```
verify that the Kogito Maven archetype is generating the project and compiling it correctly when runtime is springboot
```

**Comment by radtriste** [comment]
@spolti that is what @ricardozanini report in https://github.com/kiegroup/kogito-runtimes/pull/1508

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
ok, so I guess we can merge this one?

**Comment by ricardozanini** [comment]
> ok, so I guess we can merge this one?

Since we merged the fix today, this night we should have the new snapshots with the fix? So I think we will be good to merge on Monday?

But let's see..

/jenkins test

**Comment by ricardozanini** [comment]
jenkins retest this

**Comment by ricardozanini** [comment]
Future @radtriste, in your Monday morning, can you kick this again? Since I merged the fix today, I believe that it's not there yet.

**Comment by ricardozanini** [comment]
jenkins retest this

**Pull request merged**
