### PR TITLE
KOGITO-8538 Correct parallel Cekit tests

### PR DESCRIPTION
**Pull request by radtriste**
Use different python virtualenv for each build/test

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>

- <b>Prod tests</b>  
  Please add comment: <b>Jenkins (re)run [prod|Prod|PROD]</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by kie-ci1** [comment]
**PR job** `#443` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/443/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Fri Jan 27 04:11:07 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Fri Jan 27 04:11:07 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/443/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci1** [comment]
**PR job** `#444` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/444/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Fri Jan 27 04:35:45 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Fri Jan 27 04:35:45 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/444/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci1** [comment]
**PR job** `#445` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/445/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Fri Jan 27 08:13:02 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Fri Jan 27 08:13:02 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/445/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci1** [comment]
**PR job** `#447` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/447/display/redirect

**Test results:**
- PASSED: 249
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/447/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
local variable 'exception_cause' referenced before assignment
</details>

**Comment by kie-ci1** [comment]
**PR job** `#448` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/448/display/redirect

**Test results:**
- PASSED: 3
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/448/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
local variable 'exception_cause' referenced before assignment
</details>

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#451` was: **ABORTED**
Possible explanation: Most probably a timeout, please review

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/451/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] // parallel<br/>[Pipeline] }<br/>Click here to forcibly terminate running steps<br/>[Pipeline] // script<br/>Post stage<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>No test report files were found. Configuration error?<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f c69beb65ff17<br/>c69beb65ff17<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f cf9822d75eb0 cf9822d75eb0 cf9822d75eb0 35585f3ca6c6<br/>Untagged: quay.io/kiegroup/kogito-swf-builder:2.0<br/>Untagged: quay.io/kiegroup/kogito-swf-builder:2.0.0-snapshot<br/>Untagged: quay.io/kiegroup/kogito-swf-builder:latest<br/>Deleted: sha256:cf9822d75eb0e7c88e83710be8fcfa3c895f3a4751eb3ef65fa79d22ff8676c2<br/>Deleted: sha256:b9a39e1cdee194fa05772cb34526f7de0204916659b782310a9530f2066ee429<br/>Untagged: registry.access.redhat.com/ubi8/ubi-minimal:latest<br/>Untagged: registry.access.redhat.com/ubi8/ubi-minimal@sha256:e7ac72a1704622c46ca2f21f6d2aac3770b9408fa3add45f9d37008dad8f24ec<br/>Deleted: sha256:35585f3ca6c6847198b43439fb1ead4816288ccb6c36e42feeb7bdffe431f5a0<br/>Deleted: sha256:d7857416962e58fcc94f31256fbab5ae9f73a69c71f96947e4ad94fade71a779<br/>Error: No such image: cf9822d75eb0<br/>Error: No such image: cf9822d75eb0<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/451/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci1** [comment]
**PR job** `#452` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/452/display/redirect

**Test results:**
- PASSED: 3
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/452/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
local variable 'exception_cause' referenced before assignment
</details>

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#456` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/456/display/redirect

**Test results:**
- PASSED: 3
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/456/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
("Phrase '1' was not found in the output of running the 'sh -c 'ls /home/kogito/.m2/repository/io/quarkus/quarkus-bom  | wc -l'' command", None, '')
</details>

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#457` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/457/display/redirect

**Test results:**
- PASSED: 3
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/457/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
("Phrase '1' was not found in the output of running the 'sh -c 'ls /home/kogito/.m2/repository/io/quarkus/quarkus-bom  | wc -l'' command", None, '')
</details>

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#458` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/458/display/redirect

**Test results:**
- PASSED: 3
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/458/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
("Phrase '1' was not found in the output of running the 'sh -c 'ls /home/kogito/.m2/repository/io/quarkus/quarkus-bom  | wc -l'' command", '4\n', '')
</details>

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#459` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/459/display/redirect

**Test results:**
- PASSED: 3
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/459/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
("Phrase '1' was not found in the output of running the 'sh -c 'ls /home/kogito/.m2/repository/io/quarkus/quarkus-bom  | wc -l'' command", '4\n', '')
</details>

**Comment by kie-ci1** [comment]
**PR job** `#460` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/460/display/redirect

**Test results:**
- PASSED: 3
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/460/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
("Phrase '1' was not found in the output of running the 'sh -c 'ls /home/kogito/.m2/repository/io/quarkus/quarkus-bom  | wc -l'' command", '4\n', 'Output not found with timeout 0')
</details>

**Comment by kie-ci1** [comment]
**PR job** `#461` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/461/display/redirect

**Test results:**
- PASSED: 3
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/461/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
("Phrase '1' was not found in the output of running the 'sh -c 'ls /home/kogito/.m2/repository/io/quarkus/quarkus-bom  | wc -l'' command", '4\n', 'Output not found with timeout 0')
</details>

**Comment by radtriste** [comment]
Failing test has been commented as part of https://github.com/kiegroup/kogito-images/pull/1403
https://issues.redhat.com/browse/KOGITO-8555 is follow-up on this

**Pull request closed without merging**
