### PR TITLE
[1.11.x] [KOGITO-5851] - Build and deploy Quarkus from source files cannot be …

### PR DESCRIPTION
**Pull request by spolti**
…accessed once running on Openshift
See: https://issues.redhat.com/browse/KOGITO-5851

cherry-picks: https://github.com/kiegroup/kogito-images/pull/719

Signed-off-by: spolti <fspolti@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
See my comments on https://github.com/kiegroup/kogito-images/pull/719#pullrequestreview-749923295

**Comment by spolti** [comment]
Failure is not related:
```
features/image/data-index/kogito-data-index-postgresql.feature:18  verify if of container is correctly started with postgresql parameters
```

**Review by radtriste — APPROVED** [review]

**Review by vaibhavjainwiz — APPROVED** [review]

**Comment by radtriste** [comment]
corrected image should be available by today EOD

**Pull request merged**
