### PR TITLE
Remove dev-v1 reference from dev mode  test

### PR DESCRIPTION
**Pull request by nmirasch**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[Issue XXXX] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#9` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/9/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)<br/>	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:871)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:377)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to builds48<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1787)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1003)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)<br/>		at jdk.internal.reflect.GeneratedMethodAccessor826.invoke(Unknown Source)<br/>		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>		at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:138)<br/>		at com.sun.proxy.$Proxy205.execute(Unknown Source)<br/>		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1222)<br/>		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)<br/>		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>		at java.base/java.lang.Thread.run(Thread.java:829)<br/>[Pipeline] deleteDir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/9/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#10` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/10/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)<br/>	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:871)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:377)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to builds59<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1787)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1003)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)<br/>		at jdk.internal.reflect.GeneratedMethodAccessor826.invoke(Unknown Source)<br/>		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>		at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:138)<br/>		at com.sun.proxy.$Proxy205.execute(Unknown Source)<br/>		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1222)<br/>		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)<br/>		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>		at java.base/java.lang.Thread.run(Thread.java:829)<br/>[Pipeline] deleteDir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/10/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#16` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/16/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)<br/>	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:871)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:377)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to builds58<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1787)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1003)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)<br/>		at jdk.internal.reflect.GeneratedMethodAccessor826.invoke(Unknown Source)<br/>		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>		at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:138)<br/>		at com.sun.proxy.$Proxy205.execute(Unknown Source)<br/>		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1222)<br/>		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)<br/>		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>		at java.base/java.lang.Thread.run(Thread.java:829)<br/>[Pipeline] deleteDir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/16/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
@nmirasch the CI won't run because we can't find a fork with the name:

```
stderr: remote: Repository not found.
fatal: repository 'https://github.com/nmirasch/incubator-kie-kogito-images.git/' not found
```

Can you remane your fork as a workaround so that we can run the CI? It's an issue we are tracking here: https://github.com/apache/incubator-kie-kogito-images/issues/1729

**Comment by kie-ci3** [comment]
**PR job** `#17` was: **ABORTED**
Possible explanation: Most probably a timeout, please review

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/17/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Build KIE » kogito » main » pullrequest » kogito-images.build-image #83 completed: ABORTED<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #84 completed: ABORTED<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #79 completed: ABORTED<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #78 completed: ABORTED<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #81 completed: ABORTED<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-ephemeral<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #82 completed: ABORTED<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image #80 completed: ABORTED<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-ephemeral<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-postgresql<br/>[Pipeline] }<br/>Failed in branch kogito-jit-runner<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-postgresql<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-base-builder<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-allinone<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/17/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by wmedvede — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#18` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/18/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/nmirasch/incubator-kie-kogito-images<br/> * branch              fix_dev_v1_ref -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/nmirasch/incubator-kie-kogito-images fix_dev_v1_ref<br/>        Target: 7becdbf3 Rename quay to docker in image bundles (#1768)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/18/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
@nmirasch can you please rebase?

**Comment by kie-ci3** [comment]
**PR job** `#24` was: **ABORTED**
Possible explanation: Most probably a timeout, please review

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/24/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
ERROR: node block still appears to be neither running nor scheduled; cancelling<br/>ERROR: node block appears to be neither running nor scheduled; will cancel if this condition persists<br/>ERROR: node block still appears to be neither running nor scheduled; cancelling<br/>Pausing (Preparing for shutdown)Resuming build at Mon May 27 19:13:22 UTC 2024 after Jenkins restart<br/><br/>Waiting for reconnection of builds47 before proceeding with build<br/>Timeout expired 7 hr 42 min ago<br/>Cancelling nested steps due to timeout<br/>Ready to run at Mon May 27 19:32:08 UTC 2024<br/>Resuming (Shutdown was canceled)<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1767 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1767 completed: ABORTED<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-allinone<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1767 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1767 completed: ABORTED<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-ephemeral<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1767 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1767 completed: ABORTED<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-postgresql<br/>Body did not finish within grace period; terminating with extreme prejudice<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/24/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
Once Jenkins come back to live, I'll restart the build.

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/2/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/nmirasch/incubator-kie-kogito-images<br/> * branch              fix_dev_v1_ref -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/nmirasch/incubator-kie-kogito-images fix_dev_v1_ref<br/>        Target: 431715cd Add @jstastny-cz and @rodrigonull to CODEOWNERS (#1771)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/2/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by domhanak — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#6` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/6/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/nmirasch/incubator-kie-kogito-images<br/> * branch              fix_dev_v1_ref -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/nmirasch/incubator-kie-kogito-images fix_dev_v1_ref<br/>        Target: 530f498e Fix dockerhub image name (#1774)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/6/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Pull request merged**
