### PR TITLE
[1.27.x] Change branch to 1.25

### PR DESCRIPTION
**Pull request by antncl**
Change branch to 1.25 based on https://issues.redhat.com/browse/SPCLOUD-5300

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by rgdoliveira — APPROVED** [review]

**Comment by spolti** [comment]
@AntStephenson why this change is needed?
will we need to do it for every release?

**Comment by kie-ci1** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.27.x/job/pullrequest/job/kogito-images/4/display/redirect

**Test results:**
- PASSED: 237
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.27.x/job/pullrequest/job/kogito-images/4/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

**Comment by antncl** [comment]
> @AntStephenson why this change is needed? will we need to do it for every release?

At the present time yes, it will need to be for every release, I guess @rgdoliveira should check if in future releases you can just use a more generic branch like we did in RHPAM. I suggest we keep it consistent with the rest of serverless for now.

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
`
Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.12.0.Final:build (default) on project myproject: Failed to build quarkus application: java.lang.IllegalArgumentException: Build step 'org.kie.kogito.addon.cloudevents.quarkus.deployment.KogitoAddOnMessagingProcessor#verifyCapabilities' does not produce any build item and thus will never get executed. Either change the return type of the method to a build item type, add a parameter of type BuildProducer<[some build item type]>/Consumer<[some build item type]>, or annotate the method with @Produces. Use @Produce(EmptyBuildItem.class) if you want to always execute this step. -> [Help 1
`

It shouldn't be happening in this branch.

@radtriste is there any update missing?

**Comment by radtriste** [comment]
well yes it would happen because 1.27.x is using the Quarkus platform 2.12.0 which is using only Kogito 1.26 ...

**Comment by radtriste** [comment]
To solve this in community, we should update to Quarkus 2.12.1 (but does not occur here because we use RHBQ 2.7 for productization)

**Pull request merged**
