### PR TITLE
[KOGITO-6333] Enforce Jackson RestEasy in auto-generated projects

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-6333

Instead of adding just for SW, let's make sure that every generated project has the dependency as well to avoid failing in the integration tests since now the rest generation is optional.

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by radtriste — APPROVED** [review]
This looks good from code.

For the tests, some might fail due to https://issues.redhat.com/browse/KOGITO-6330

**Review by sutaakar — APPROVED** [review]

**Comment by ricardozanini** [comment]
I can see that we have failed native tests, but I can't see why. The only log available as far as I could find, is the building one. The image has been built, but the runtime log information I couldn't find it. How can I see the logs that justify the `500` status code?

**Comment by spolti** [comment]
should we wait  https://issues.redhat.com/browse/KOGITO-6330 to get fixed?

**Comment by ricardozanini** [comment]
> should we wait https://issues.redhat.com/browse/KOGITO-6330 to get fixed?

oh I see

I don't think so, @spolti 

The kogito-builder IT already covered this use case. I was just worried about the native compilation error being related to my changes. I don't think they are related, so you can go ahead and merge this.

**Review by spolti — APPROVED** [review]

**Pull request merged**
