### PR TITLE
[0.9.x][KOGITO-1673] - Images should deploy version without micro version in tag

### PR DESCRIPTION
**Pull request by spolti**
See: https://issues.redhat.com/browse/KOGITO-1673
cherry picked from: https://github.com/kiegroup/kogito-images/pull/124

Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by radtriste** [comment]
can you add the branch into the title and also correct the title with the one from the issue ?

add also the other PR from which it has been cherry-picked

**Comment by spolti** [comment]
I would prefer use labels for it, for this one we can do this way, will setup new labes later for it.

**Comment by radtriste** [comment]
for the version as usually master and the branch (0.9.x) will have the same name, it is a way to distinguish in emails/notifications ...

cherry-pick can stay into the labels.

also, please update the title with the one from issue: `Images should deploy version without micro version in tag`

**Comment by spolti** [comment]
right, forget the tittle :)

**Review by radtriste — APPROVED** [review]

**Pull request merged**
