### PR TITLE
BXMSPROD-1579 Send build summary as PR comment

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/BXMSPROD-1579

Depends on https://github.com/kiegroup/kogito-pipelines/pull/340

Related PRs:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/179
- https://github.com/kiegroup/kogito-pipelines/pull/340
- https://github.com/kiegroup/kogito-images/pull/1043
- https://github.com/kiegroup/kogito-operator/pull/1120

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** #9 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 16
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/test-pr-check-send-comment-kogito-images/9/testReport/features.image.common/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_runtime_native___Test_kogito_runtime_native___Verify_if_Kogito_user_is_correctly_configured/">Build & Test Images / Build&Test kogito-runtime-native / Test kogito-runtime-native / features.image.common.Common tests for Kogito images.Verify if Kogito user is correctly configured</a></summary>
("Phrase '/home2/kogito' was not found in the output of running the 'sh -c 'echo $HOME'' command", None)
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/test-pr-check-send-comment-kogito-images/9/testReport/features.image.common/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_runtime_jvm___Test_kogito_runtime_jvm___Verify_if_Kogito_user_is_correctly_configured/">Build & Test Images / Build&Test kogito-runtime-jvm / Test kogito-runtime-jvm / features.image.common.Common tests for Kogito images.Verify if Kogito user is correctly configured</a></summary>
("Phrase '/home2/kogito' was not found in the output of running the 'sh -c 'echo $HOME'' command", None)
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/test-pr-check-send-comment-kogito-images/9/display/redirect or see console log:
```spoiler Console Logs
+ date
Thu Jan 20 17:05:03 EST 2022
[Pipeline] sh
++ docker images -q
+ docker rmi -f 3d04b00e676a aaba47b0a43d 4c5a9f61e184 5a937292d732 211a7bd6fb21 75fe5d543727 75fe5d543727 75fe5d543727 f46e2948dc3a f46e2948dc3a f46e2948dc3a 06e83dd71843 0e1c0c70dbc5
Untagged: integ-quay.io/kiegroup/kogito-runtime-jvm:2.0.0-snapshot
Deleted: sha256:3d04b00e676a7d907db85573aab8f6a45191e15a8d011a6f641246e87a58f2cd
Deleted: sha256:0f3d1d98bad1b08677ad8b22bb6ac159a737f7b14ca1f49af59d44efd2a120fd
Deleted: sha256:aaba47b0a43dec7e56ea8f3f82f28c422349ce9f2986b42234c99bd37e5912f5
Deleted: sha256:57da55550f8d5cb4880efc8b270f259c373a884066fb91bf13c763b38835d494
Deleted: sha256:4c5a9f61e184efb39f4b8924e3d352325dac692d9131ce4ae1b1918729230bc0
Deleted: sha256:14d7ab9e0997e04d53414ca02c5d633b62818379ea3eb4022958bb26a634f388
Deleted: sha256:5a937292d732b26b47a13186c6948eceb16770e2fb4730a55483cfab288abe94
Deleted: sha256:910787bb238eefcd9939007e7b506e2ced357385b6debf46f9f5a3778ec13148
Untagged: integ-quay.io/kiegroup/kogito-runtime-native:2.0.0-snapshot
Deleted: sha256:211a7bd6fb2129e5fe22ace110e93ab63097f0135c3360366de9f9617705b22c
Deleted: sha256:6d34b99a9a31f1fd1e31bdf668e13e996f7b8d666b656806c66b625d18da508f
Untagged: quay.io/kiegroup/kogito-runtime-jvm:2.0
Untagged: quay.io/kiegroup/kogito-runtime-jvm:2.0.0-snapshot
Untagged: quay.io/kiegroup/kogito-runtime-jvm:latest
Deleted: sha256:75fe5d543727dc8ba1be6b4ca0359f164abb99be9746b1e1a68ea920f4415bab
Deleted: sha256:467e986ad05463ae794120f41831ad8554e0c0dbd0723b8b3be8e294acc015f2
Untagged: quay.io/kiegroup/kogito-runtime-native:2.0
Untagged: quay.io/kiegroup/kogito-runtime-native:2.0.0-snapshot
Untagged: quay.io/kiegroup/kogito-runtime-native:latest
Deleted: sha256:f46e2948dc3ae411fd1361d41042618b9be55fba3209608b40f19fbb63d18189
Deleted: sha256:16480683810f46f8c03d98fc296807b00aa7874d109244432738b7856df5f6e9
Untagged: quay.io/quarkus/ubi-quarkus-native-image:21.3-java11
Untagged: quay.io/quarkus/ubi-quarkus-native-image@sha256:bd1b7e3e81b60239611eaae77aa390150b33da7fc4fb91028dee4034f1b5ab0e
Deleted: sha256:06e83dd7184349402cf880e47e476c8d6b47a6383145328ec2abbf63030d303e
Deleted: sha256:db9f9d2843820470def28eea052fb9c6128113ac156211c8f2e385d4437bb785
Untagged: registry.access.redhat.com/ubi8/ubi-minimal:latest
Untagged: registry.access.redhat.com/ubi8/ubi-minimal@sha256:cf1c63e3247e4074ee3549a064b8798a1a2513ad57dd79c9edb979836355b469
Deleted: sha256:0e1c0c70dbc541d61917f91e6ad3d05b82762c5a9b49774571f2a87d8f09be65
Deleted: sha256:d7b78388bf5355f416a0420994e81510497aa4851cca6d0ff2690fa8357003f2
Deleted: sha256:e8228e50fe1805fb75cf22886a451b94982b6beea5c04ddcf24d1d2302200449
Error: No such image: 75fe5d543727
Error: No such image: 75fe5d543727
Error: No such image: f46e2948dc3a
Error: No such image: f46e2948dc3a
[Pipeline] sh
+ rm -rf /home/jenkins/.cekit/cache
[Pipeline] }
[Pipeline] // script
[Pipeline] script
[Pipeline] {
[Pipeline] sh
+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/test-pr-check-send-comment-kogito-images/9/api/json
[Pipeline] readJSON
[Pipeline] sh

```

**Comment by kie-ci1** [comment]
**PR job** #10 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 16
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/test-pr-check-send-comment-kogito-images/10/testReport/features.image.common/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_runtime_native___Test_kogito_runtime_native___Verify_if_Kogito_user_is_correctly_configured/">Build & Test Images / Build&Test kogito-runtime-native / Test kogito-runtime-native / features.image.common.Common tests for Kogito images.Verify if Kogito user is correctly configured</a></summary>
("Phrase '/home2/kogito' was not found in the output of running the 'sh -c 'echo $HOME'' command", None)
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/test-pr-check-send-comment-kogito-images/10/testReport/features.image.common/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_runtime_jvm___Test_kogito_runtime_jvm___Verify_if_Kogito_user_is_correctly_configured/">Build & Test Images / Build&Test kogito-runtime-jvm / Test kogito-runtime-jvm / features.image.common.Common tests for Kogito images.Verify if Kogito user is correctly configured</a></summary>
("Phrase '/home2/kogito' was not found in the output of running the 'sh -c 'echo $HOME'' command", None)
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/test-pr-check-send-comment-kogito-images/10/display/redirect

**Comment by radtriste** [comment]
depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/179

**Comment by kie-ci1** [comment]
**PR job** #11 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 234
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/test-pr-check-send-comment-kogito-images/11/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_trusty_ui___Test_kogito_trusty_ui___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-trusty-ui / Test kogito-trusty-ui / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/test-pr-check-send-comment-kogito-images/11/display/redirect

**Comment by radtriste** [comment]
jenkins retest this

**Review by sutaakar — APPROVED** [review]

**Review by spolti — APPROVED** [review]
Nice work Tristan :)

**Pull request merged**
