### PR TITLE
KOGITO-2767 Fix master to 1.0.0-snapshot version

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-2767

Similarly to https://github.com/kiegroup/kogito-cloud-operator/pull/484

Fixing 1.0.0-snapshot version to master.

Depends on https://github.com/kiegroup/kogito-apps/pull/358

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins retest this

**Review by ricardozanini — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
looks like `dmn-quarkus-example` is having problems to compile in native via archetype ... I am checking that

**Review by Kaitou786 — APPROVED** [review]

**Comment by radtriste** [comment]
This is the issue in runtimes: https://issues.redhat.com/browse/KOGITO-2968
On our side, images should remove that `test-process.bpmn2` as it is useless and should not be taken into account. Gonna update the PR.

**Comment by radtriste** [comment]
@spolti and now we are good to merge :)

**Pull request merged**
