### PR TITLE
[KOGITO-951] Refactor KubernetesServiceDiscoveryIntegrationTest to us…

### PR DESCRIPTION
**Pull request by sutaakar**
…e mocked OpenShift client

https://issues.redhat.com/browse/KOGITO-951

Signed-off-by: Karel Suta <ksuta@redhat.com>

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this

**Review by radtriste — APPROVED** [review]
lgtm

**Comment by sutaakar** [comment]
@spolti Can you please take a look and possibly merge?

**Review by spolti — CHANGES_REQUESTED** [review]
looks good to me, but just a minor thing, do you mind to change the kieserver occurrences to kogito?

**Comment by sutaakar** [comment]
@spolti  Good catch, I completely overlooked that :)
PR adjusted

**Review by spolti — APPROVED** [review]

**Pull request merged**
