### PR TITLE
KOGITO-9654: Include kogito-addons-quarkus-process-management in kogito-swf-devmode-image

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/KOGITO-9654

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>

- <b>Prod tests</b>  
  Please add comment: <b>Jenkins (re)run [prod|Prod|PROD]</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by manstis** [comment]
Hi @radtriste I've not had to change anything here for literally years.

Could you please have a look for me? Thank-you.

**Comment by manstis** [comment]
Hmmm. I'm clearly missing something.

**Comment by kie-ci1** [comment]
**PR job** `#1022` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1022/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-task-console: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-swf-devmode: https://github.com/kiegroup/kogito-images/pull/1655 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-devmode seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-s2i-builder: https://github.com/kiegroup/kogito-images/pull/1655 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-s2i-builder seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1022/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by manstis** [comment]
Jenkins test this

**Comment by manstis** [comment]
Jenkins (re)run kogito-swf-devmode tests

**Comment by kie-ci1** [comment]
**PR job** `#1023` was: **ABORTED**
Possible explanation: Most probably a timeout, please review

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1023/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-swf-builder: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-s2i-builder: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Cancelling nested steps due to timeout<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-swf-devmode: https://github.com/kiegroup/kogito-images/pull/1655 completed: ABORTED<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1023/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by manstis** [comment]
Jenkins test this

**Comment by kie-ci1** [comment]
**PR job** `#1025` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1025/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-management-console: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-s2i-builder: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-swf-devmode: https://github.com/kiegroup/kogito-images/pull/1655 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-devmode seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1025/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by radtriste** [comment]
jenkins retest this

**Comment by manstis** [comment]
Thank-you @radtriste.

Sadly this is the second time the whole build failed _just_ due to `kogito-swf-devmode` failing.

I don't see why; the logs _imply_ the container is failing to start (as `q/health` times out repeatedly).

However there's nothing to suggest _why_ the container probably failed to start.

From what I know I've made enough changes to include the new addon.

**Comment by kie-ci1** [comment]
**PR job** `#1028` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1028/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-task-console: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-s2i-builder: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-swf-devmode: https://github.com/kiegroup/kogito-images/pull/1655 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-devmode seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1028/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by radtriste** [comment]
> build failed _just_ due to `kogito-swf-devmode` failing.
> 
> I don't see why; the logs _imply_ the container is failing to start (as `q/health` times out repeatedly).
> 
> However there's nothing to suggest _why_ the container probably failed to start.

@manstis This needs deeper investigation
Did you try to build the devmode locally and run it ?
I can have a look today or tomorrow

**Comment by manstis** [comment]
Hello @radtriste, if there's a way to build it locally I am very happy to do so. I tried building the whole repository locally but I remember it failing elsewhere (I.e. not `kogito-swf-devmode`). Can you advise?

**Comment by radtriste** [comment]
> Hello @radtriste, if there's a way to build it locally I am very happy to do so. I tried building the whole repository locally but I remember it failing elsewhere (I.e. not `kogito-swf-devmode`). Can you advise?

https://github.com/kiegroup/kogito-images/tree/main#building-images ;)
You will need Cekit installed on your machine

**Comment by manstis** [comment]
Sorry @radtriste IDK if `kogito-swf-devmode` is supported?
```
> make build-image image_name=kogito-swf-devmode
cd tests/test-apps && export CONTAINER_ENGINE=docker && sh clone-repo.sh true kogito-swf-devmode
Target image is supporting services, skipping examples build
cd ../..
scripts/build-kogito-apps-components.sh kogito-swf-devmode main https://github.com/kiegroup/kogito-apps.git;
kogito-swf-devmode is not a supporting service image or can't be built from sources, exiting...
cekit -v  --descriptor kogito-swf-devmode-image.yaml build  docker
make: cekit: No such file or directory
make: *** [Makefile:44: _build-image] Error 127
```

**Comment by radtriste** [comment]
```
make: cekit: No such file or directory
```
https://docs.cekit.io/en/latest/getting-started/index.html

**Comment by manstis** [comment]
Thanks @radtriste I'd forgotten to _activate_ my Python `venv`.

**Comment by manstis** [comment]
Hi @fjtirado 

This PR attempts to build the `kogito-swf-devmode` image with the `kogito-addons-quarkus-process-management` included.

Quarkus is however failing to startup with the addon due to the following error:
```
2023-08-01 09:55:06,569 cbc5beb49f86 ERROR [io.quarkus.deployment.dev.IsolatedDevModeMain:231] (vert.x-worker-thread-10) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.process.Processes and qualifiers [@Default]
	- java member: org.kie.kogito.process.management.ProcessInstanceManagementResource():processes
	- declared on CLASS bean [types=[java.lang.Object, org.kie.kogito.process.management.ProcessInstanceManagementResource], qualifiers=[@Default, @Any], target=org.kie.kogito.process.management.ProcessInstanceManagementResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1223)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:288)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:148)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:526)
	at jdk.internal.reflect.GeneratedMethodAccessor733.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```
It looks like an additional dependency is needed somewhere for implementations of `Processes processes`?

**Comment by tiagodolphine** [comment]
> Hi @fjtirado
> 
> This PR attempts to build the `kogito-swf-devmode` image with the `kogito-addons-quarkus-process-management` included.
> 
> Quarkus is however failing to startup with the addon due to the following error:
> 
> ```
> 2023-08-01 09:55:06,569 cbc5beb49f86 ERROR [io.quarkus.deployment.dev.IsolatedDevModeMain:231] (vert.x-worker-thread-10) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.kie.kogito.process.Processes and qualifiers [@Default]
> 	- java member: org.kie.kogito.process.management.ProcessInstanceManagementResource():processes
> 	- declared on CLASS bean [types=[java.lang.Object, org.kie.kogito.process.management.ProcessInstanceManagementResource], qualifiers=[@Default, @Any], target=org.kie.kogito.process.management.ProcessInstanceManagementResource]
> 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1223)
> 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:288)
> 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:148)
> 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:526)
> 	at jdk.internal.reflect.GeneratedMethodAccessor733.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
> 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
> 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
> ```
> 
> It looks like an additional dependency is needed somewhere for implementations of `Processes processes`?

This should fix the issue
https://github.com/kiegroup/kogito-runtimes/pull/3154

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#1031` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1031/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
<br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/manstis/kogito-images KOGITO-9654<br/>        Target: 45ff4bd9 Fix Spring Boot incremental testing (#1652)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1031/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by radtriste** [comment]
@manstis could you rebase ? :)

**Comment by kie-ci1** [comment]
**PR job** `#1033` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1033/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-swf-builder: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-task-console: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-swf-devmode: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1655 - kogito-s2i-builder: https://github.com/kiegroup/kogito-images/pull/1655 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/1033/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by radtriste** [comment]
jenkins retest this

**Comment by manstis** [comment]
@radtriste @tiagodolphine It's only gone and turned green :smile:

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
@spolti please check, approve and merge

**Comment by tiagodolphine** [comment]
we need to merge this one asap, @spolti do you want to review it? CI is green already.
thanks.

**Review by spolti — APPROVED** [review]

**Pull request merged**
