### PR TITLE
Updating references to the new kie-ci actions folder.

### PR DESCRIPTION
**Pull request by bacciotti**
Related PR's
- https://github.com/kiegroup/kie-ci/pull/1495
- https://github.com/kiegroup/kogito-images/pull/1543
- https://github.com/kiegroup/kogito-images/pull/1544

### CODE REVIEW

**Comment by spolti** [comment]
@bacciotti what is the status of it?
Can we merge?

@rgdoliveira

**Comment by bacciotti** [comment]
@spolti from my side it is ok. Let's just wait for approval, wdyt?

**Review by lampajr — APPROVED** [review]

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by spolti** [comment]
does it needs to be cherry-picked to 1.13.x-next and 1.13.x-blue-next branches?

**Comment by bacciotti** [comment]
@spolti yes, I guess it does.

**Comment by spolti** [comment]
same here

**Comment by radtriste** [comment]
backports could not be done. I guess a manual update is needed @bacciotti

**Comment by bacciotti** [comment]
I created 2 new PR's with the suggestions and they are in the main comment.

**Pull request merged**
