### PR TITLE
kie-issues#821: Kogito-images weekly job 

### PR DESCRIPTION
**Pull request by rodrigonull**
ISSUE: https://github.com/apache/incubator-kie-issues/issues/821

This PR introduces a new weekly Jenkins job for Kogito Images that updates the project version to 999-YYYYMMDD-SNAPSHOT locally, build the kogito-swf-devmode image and push it to quay.io

The weekly job also creates a new tag in the repo with this format: 999-YYYYMMDD.

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#79` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/79/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-data-index-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-management-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-runtime-jvm: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-s2i-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/79/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#80` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/80/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-management-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-runtime-jvm: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-s2i-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/80/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#83` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/83/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-runtime-jvm: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-data-index-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-management-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-s2i-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/83/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#88` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/88/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-management-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-s2i-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/88/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by jstastny-cz — APPROVED** [review]
LGTM

**Comment by kie-ci3** [comment]
**PR job** `#90` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/90/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-management-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-allinone seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1740 - kogito-s2i-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1740 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/90/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by cimbalek — APPROVED** [review]

**Pull request merged**
