### PR TITLE
[KOGITO-2353] - Add option to run the kogito images' bats tests using…

### PR DESCRIPTION
**Pull request by Kaitou786**
… make command

See: https://issues.redhat.com/browse/KOGITO-2353

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by radtriste — APPROVED** [review]
lgtm

**Review by ricardozanini — APPROVED** [review]

**Comment by Kaitou786** [comment]
Jenkins, retest this please

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
@Kaitou786 as you are changing the bats tests, do you mind to rename the "Run S2i..." workflow to just "Run modules Bats..."?

**Comment by Kaitou786** [comment]
@spolti okay, I'll change that. Also as we are running both the action  always, is it okay if i define them in a single file and use workflows with them? Just like we've coupled on the kogito-cloud-operator?

**Comment by spolti** [comment]
@Kaitou786 that's fine :)

**Comment by Kaitou786** [comment]
Jenkins, retest this please

**Comment by Kaitou786** [comment]
@spolti CI passed here :-)

**Review by spolti — APPROVED** [review]

**Pull request merged**
