### PR TITLE
[1.10.x] Fix Quarkus registry issue

### PR DESCRIPTION
**Pull request by radtriste**
Cherry-pick from https://github.com/kiegroup/kogito-images/pull/631

Include also fix for https://issues.redhat.com/browse/KOGITO-5671

This should solve the serverless archetype builder test

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
- Mongodb error is a known problem: https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/jobs-service-mongodb.20does.20not.20connect.20to.20Mongodb

**Comment by radtriste** [comment]
@ricardozanini getting on serverless test:
```
2021-08-06 06:29:47,724 - root - INFO - Response code from the container on port 8080: 400 (expected: 200)
```
So I guess the change got in ...

**Comment by radtriste** [comment]
Mongodb issue will be corrected in https://issues.redhat.com/browse/KOGITO-5671
Can be merged after approval

**Review by ricardozanini — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Comment by radtriste** [comment]
@spolti can be merged when you want

**Comment by ricardozanini** [comment]
> @ricardozanini getting on serverless test:
> 
> ```
> 2021-08-06 06:29:47,724 - root - INFO - Response code from the container on port 8080: 400 (expected: 200)
> ```
> 
> So I guess the change got in ...

Just to not let this one unanswered, this error should be fixed by the `content-type` that you've added to the SW test. The one with groovy did not make the 1.10.x cut.

**Pull request merged**
