### PR TITLE
KOGITO-2993: Quarkus 1.7.0 => Bump GraalVM to 20.1.0

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-2993
Description: Quarkus 1.7.0 => Bump GraalVM to 20.1.0

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by radtriste — APPROVED** [review]
lgtm

**Comment by Sgitario** [comment]
Jenkins, test this

**Comment by radtriste** [comment]
Jenkins test this

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
ci is complaining:
sh: /tmp/scripts/org.kie.kogito.graalvm.installer/configure: No such file or directory

**Comment by radtriste** [comment]
yep missed that. `module.yaml` were moved but not `configure` files

**Comment by Sgitario** [comment]
> yep missed that. `module.yaml` were moved but not `configure` files

Added.

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins test this

**Pull request merged**
