### PR TITLE
Updated reviewers bot file

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Comment by radtriste** [comment]
Jenkins retest this

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
Yey @vaibhavjainwiz :D

**Comment by spolti** [comment]
Thanks @radtriste :)

**Comment by radtriste** [comment]
looks like there is a problem on building examples (but not related to this PR ...)

**Comment by radtriste** [comment]
@spolti can we merge this one ?

**Comment by spolti** [comment]
yep.

**Comment by spolti** [comment]
@radtriste wondering if there is a way to ignore tests if the files changed does touch files not related with the images.

**Pull request merged**
