### PR TITLE
[KOGITO-7376] - [SW] Move SW examples to kogito-examples root

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: spolti <fspolti@redhat.com>
https://issues.redhat.com/browse/KOGITO-7376

Depends on https://github.com/kiegroup/kogito-examples/pull/1292

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by kie-ci1** [comment]
**PR job** `#10` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/10/display/redirect

**Test results:**
- PASSED: 237
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/10/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

**Review by ricardozanini — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#11` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/11/display/redirect

**Test results:**
- PASSED: 234
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/11/testReport/features.image.kogito-builder-native/kogito-builder image native build tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_using_native_build/">features.image.kogito-builder-native.kogito-builder image native build tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly using native build</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/11/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/11/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_with_custom_group_id,_archetype___version/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly with custom group id, archetype & version</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/11/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

**Comment by radtriste** [comment]
there is a maven mirror issue. 

jenkins retest this

**Comment by spolti** [comment]
> there is a maven mirror issue.
> 
> jenkins retest this

I was going to ask about it, I didn't find any apparent issue on the logs :)

**Comment by kie-ci1** [comment]
**PR job** `#12` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/12/display/redirect

**Test results:**
- PASSED: 234
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/12/testReport/features.image.kogito-builder-native/kogito-builder image native build tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_using_native_build/">features.image.kogito-builder-native.kogito-builder image native build tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly using native build</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/12/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/12/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_with_custom_group_id,_archetype___version/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly with custom group id, archetype & version</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/12/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

**Comment by kie-ci1** [comment]
**PR job** `#13` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/13/display/redirect

**Test results:**
- PASSED: 234
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/13/testReport/features.image.kogito-builder-native/kogito-builder image native build tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_using_native_build/">features.image.kogito-builder-native.kogito-builder image native build tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly using native build</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/13/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/13/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_with_custom_group_id,_archetype___version/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly with custom group id, archetype & version</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/13/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

**Comment by radtriste** [comment]
issue is totally normal, as the platform 2.10 is not released yet. that is why the checks are failing ...
but the path change seems to work fine
@spolti I think we can merge :)

**Comment by spolti** [comment]
ok, thanks @radtriste

**Pull request merged**
