### PR TITLE
[KOGITO-525] - Upgrade to GraalVM 19.2.1

### PR DESCRIPTION
**Pull request by ricardozanini**
See:
https://issues.jboss.org/browse/KOGITO-525

I also removed old GraalVM modules since doesn't make sense to have them right now.

We should hold to merge this until 0.5.1 image release, since it's using Quarkus 0.26. Right, @mswiderski?

### CODE REVIEW

**Comment by ricardozanini** [comment]
Refers to:
https://github.com/kiegroup/kogito-bom/pull/65

**Review by spolti — APPROVED** [review]

**Comment by mswiderski** [comment]
@ricardozanini this needs to go with 0.6.0 as now master is upgraded to 0.27.0 of quarkus

**Comment by ricardozanini** [comment]
@mswiderski sure, we're holding this PR until @spolti merge this:
https://issues.jboss.org/browse/KOGITO-521 (bump to 0.5.1). Then we will merge for 0.6.0.

**Pull request merged**
