### PR TITLE
[0.9.x][KOGITO-1828] Update Jobs-services, data-index and mgmt console SNAPSHOT artefacts

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-1828

jobs-services snapshot version: jobs-service-0.9.1-20200410.154450-11-runner.jar
md5: d7e781cbdb4b5968185699e03614a437

data-index snapshot version: data-index-service-0.9.1-20200410.154951-11-runner.jar
md5: cf5549ad15725a3a4e69f085da56683b

management-console snapshot version: management-console-0.9.1-20200410.155354-11-runner.jar
md5: afd4885e4c33884e744adaaed3e280b7

Image tag: 0.9.1-rc2

Signed-off-by: tradisso tradisso@redhat.com

### CODE REVIEW

**Comment by radtriste** [comment]
@spolti I changed version and artefacts. did I forgot anything ?

**Comment by spolti** [comment]
looks like you changed everything.

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
images pushed, tag 0.9.1-rc2

**Review by ricardozanini — APPROVED** [review]

**Comment by spolti** [comment]
@radtriste let me know when the tests are ready so we can merge this one :)

**Review by sutaakar — APPROVED** [review]

**Comment by radtriste** [comment]
tests passed

**Pull request merged**
