### PR TITLE
Upgrade of GraalVM to rc16

### PR DESCRIPTION
**Pull request by mswiderski**
@spolti could you please review?

### CODE REVIEW

**Review by spolti — APPROVED** [review]

**Comment by mswiderski** [comment]
@spolti what would be the way to get it build and pushed to quay.io?

**Comment by spolti** [comment]
@mswiderski the images are under the kiegroup organization.
To push, you can execute make push (I think you have permissions there, if not we can ask Babak or Thommy).
I can do this for you after you merge this changes.

**Comment by mswiderski** [comment]
@spolti if you could do the build and push that would be great, thanks a lot

**Comment by spolti** [comment]
@mswiderski I just pushed the new images.

**Pull request merged**
