### PR TITLE
[kie-issues#913] Upgrade to Quarkus 3.2.10.Final LTS version.

### PR DESCRIPTION
**Pull request by baldimir**
Tracker: https://github.com/apache/incubator-kie-issues/issues/913

Aligns with Quarkus 3.2.10.Final.

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#93` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/93/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)<br/>	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:871)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:377)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to builds60<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1787)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1003)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)<br/>		at jdk.internal.reflect.GeneratedMethodAccessor1120.invoke(Unknown Source)<br/>		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>		at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:138)<br/>		at com.sun.proxy.$Proxy269.execute(Unknown Source)<br/>		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1222)<br/>		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)<br/>		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>		at java.base/java.lang.Thread.run(Thread.java:829)<br/>[Pipeline] deleteDir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/93/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
@baldimir can you please rename your fork?

```
stderr: remote: Repository not found.
fatal: repository 'https://github.com/baldimir/incubator-kie-kogito-images.git/' not found
```

**Review by porcelli — APPROVED** [review]

**Comment by jstastny-cz** [comment]
> @baldimir can you please rename your fork?
> 
> ```
> stderr: remote: Repository not found.
> fatal: repository 'https://github.com/baldimir/incubator-kie-kogito-images.git/' not found
> ```

@ricardozanini We should adjust pipelines rather than asking to rename forks :-) buildchain already can do that for code repos, so it should be done also for others. Consider when we're promoted from incubation - we'd need to ask people to rename again, which is not practical.

**Comment by baldimir** [comment]
The Jenkins CI check is now failing because of https://github.com/apache/incubator-kie-issues/issues/955. @cimbalek

**Comment by ricardozanini** [comment]
> > @baldimir can you please rename your fork?
> > ```
> > stderr: remote: Repository not found.
> > fatal: repository 'https://github.com/baldimir/incubator-kie-kogito-images.git/' not found
> > ```
> 
> @ricardozanini We should adjust pipelines rather than asking to rename forks :-) buildchain already can do that for code repos, so it should be done also for others. Consider when we're promoted from incubation - we'd need to ask people to rename again, which is not practical.

Sure, we have an issue for that: #1729. I don't know where to change this, can you help?

**Comment by kie-ci3** [comment]
**PR job** `#101` was: **ABORTED**
Possible explanation: Most probably a timeout, please review

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/101/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-base-builder<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-ephemeral<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-postgresql<br/>[Pipeline] }<br/>Failed in branch kogito-jit-runner<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-allinone<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-ephemeral<br/>[Pipeline] }<br/>Failed in branch kogito-jobs-service-postgresql<br/>[Pipeline] }<br/>Failed in branch kogito-runtime-jvm<br/>[Pipeline] }<br/>Failed in branch kogito-runtime-native<br/>[Pipeline] }<br/>Failed in branch kogito-s2i-builder<br/>[Pipeline] }<br/>Failed in branch kogito-swf-builder<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>[Pipeline] }<br/>Failed in branch kogito-task-console<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/101/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#104` was: **ABORTED**
Possible explanation: Most probably a timeout, please review

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/104/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-runtime-native: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Calling Pipeline was cancelled<br/>Click here to forcibly terminate running steps<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: ABORTED<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-data-index-postgresql<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-s2i-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: ABORTED<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-s2i-builder<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/104/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by porcelli** [comment]
looks like CI is not helping 😬

**Comment by ricardozanini** [comment]
The tests failing are expected, we have issues to solve them already. They are not related, but I've restarted just in case.

**Review by yesamer — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#105` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/105/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-management-console: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-ephemeral seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-runtime-jvm: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-task-console: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1743 - kogito-s2i-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1743 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/105/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
It seems an issue fetching a few dependencies: 

```
[ERROR] Unresolveable build extension: Plugin org.kie.kogito:kogito-maven-plugin:999-SNAPSHOT or one of its dependencies could not be resolved: Failed to collect dependencies at org.kie.kogito:kogito-maven-plugin:jar:999-SNAPSHOT -> org.kie.kogito:kogito-pmml-dependencies:pom:999-SNAPSHOT -> org.kie:kie-pmml-dependencies:jar:999-SNAPSHOT -> org.kie:kie-pmml-models-mining-model:jar:999-SNAPSHOT @ 
```

**Comment by baldimir** [comment]
This doesn't look like a problem connected with the change I did. Could we merge this please?

**Pull request merged**
