### PR TITLE
KOGITO-9300: operator dev mode image shouldn't generate the kogito.yaml file

### PR DESCRIPTION
**Pull request by wmedvede**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [X] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [X] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [X] Pull Request contains link to the JIRA issue
- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket
- [X] Your feature/bug fix has a testcase that verifies it
- [X] You've tested the new feature/bug fix in an actual OpenShift cluster
- [X] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>

- <b>Prod tests</b>  
  Please add comment: <b>Jenkins (re)run [prod|Prod|PROD]</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi  @ricardozanini , after investigations in: https://github.com/kiegroup/kogito-runtimes/pull/3041

I conclude that (at the day of today) we don't need the "quarkus-kubernetes" to be packaged along the devmode image.

By executing the test on this this change we can see that the image is generated and a Scenario that include service discovery passed ok.

make build-image image_name=kogito-swf-devmode


Test run finished after 28252 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         1 tests found           ]
[         0 tests skipped         ]
[         1 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         0 tests failed          ]


**The tests include a scenario that covers the service discovery.**

  Scenario: Verify if container starts in devmode with service discovery property
    When container is started with env
      | variable          | value                                                                              |
      | SCRIPT_DEBUG      | true                                                                               |
      | MAVEN_ARGS_APPEND | **-Dkogito.dataindex.ws.url=knative:services.v1.serving.knative.dev/namespace1/test2** |

**Review by ricardozanini — APPROVED** [review]
Yay!

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
Thanks @wmedvede, before merging, do you mind updating the release_notes.md?

**Comment by kie-ci1** [comment]
**PR job** `#775` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/775/display/redirect

**Test results:**
- PASSED: 268
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/775/testReport/features.image.kogito-common-builder-jvm/kogito-s2i-builder image JVM build tests/Perform_a_second_incremental_s2i_build_using_quarkus_runtime_type/">features.image.kogito-common-builder-jvm.kogito-s2i-builder image JVM build tests.Perform a second incremental s2i build using quarkus runtime type</a></summary>
Phrase 'Expanding artifacts from incremental build...' was not found in the output of S2I
</details>

**Comment by wmedvede** [comment]
Jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#777` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/777/display/redirect

**Test results:**
- PASSED: 268
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/777/testReport/features.image.kogito-common-builder-jvm/kogito-s2i-builder image JVM build tests/Perform_a_second_incremental_s2i_build_using_springboot_runtime_type/">features.image.kogito-common-builder-jvm.kogito-s2i-builder image JVM build tests.Perform a second incremental s2i build using springboot runtime type</a></summary>
Phrase 'Expanding artifacts from incremental build...' was not found in the output of S2I
</details>

**Pull request merged**
