### PR TITLE
[1.20.x] Fix some issues for release

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by kie-ci1** [comment]
**PR job** `#9` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 233
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/9/testReport/features.image.jobs-service.kogito-jobs-service-postgresql.Kogito-jobs-service-postgresql feature//verify_if_of_container_is_correctly_started_with_postgresql_parameters/">features.image.jobs-service.kogito-jobs-service-postgresql.Kogito-jobs-service-postgresql feature..verify if of container is correctly started with postgresql parameters</a></summary>
Message 'Datasource '<default>': The connection attempt failed' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/9/testReport/features.image.kogito-builder-native/kogito-builder image native build tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_using_native_build/">features.image.kogito-builder-native.kogito-builder image native build tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly using native build</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/9/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/9/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_with_custom_group_id,_archetype___version/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly with custom group id, archetype & version</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/9/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/9/display/redirect

**Comment by kie-ci1** [comment]
**PR job** `#10` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 234
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/10/testReport/features.image.kogito-builder-native/kogito-builder image native build tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_using_native_build/">features.image.kogito-builder-native.kogito-builder image native build tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly using native build</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/10/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/10/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_with_custom_group_id,_archetype___version/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly with custom group id, archetype & version</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/10/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/10/display/redirect

**Comment by radtriste** [comment]
`kogito` is not part of Quarkus 2.8 yet, so archetype generation is failing.

**Review by spolti — APPROVED** [review]

**Comment by kie-ci1** [comment]
**PR job** `#11` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 234
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/11/testReport/features.image.kogito-builder-native/kogito-builder image native build tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_using_native_build/">features.image.kogito-builder-native.kogito-builder image native build tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly using native build</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/11/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/11/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Maven_archetype_is_generating_the_project_and_compiling_it_correctly_with_custom_group_id,_archetype___version/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Maven archetype is generating the project and compiling it correctly with custom group id, archetype & version</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/11/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.20.x/job/pullrequest/job/kogito-images/11/display/redirect

**Comment by radtriste** [comment]
I reverted to `io.quarkus.platform` groupId
There was confusion due to quarkus 2.8 platform not released yet ...

**Comment by radtriste** [comment]
> I reverted to `io.quarkus.platform` groupId There was confusion due to quarkus 2.8 platform not released yet ...

test failures are due to that

**Pull request merged**
