### PR TITLE
[KOGITO-1036] - Extract kogito-images from kogito-cloud repository

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
depends on https://github.com/kiegroup/kogito-runtimes/pull/359

**Review by ricardozanini — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by sutaakar** [comment]
@spolti I think that parent pom.xml can be deleted too,right?

**Comment by spolti** [comment]
@sutaakar yes, missed that one :)
Thanks.

**Review by sutaakar — APPROVED** [review]

**Review by cristianonicolai — COMMENTED** [review]
@spolti you also need to update the Jenkins file for this repo.

**Comment by spolti** [comment]
@cristianonicolai this Jenkins file will be replaced shortly.
Probably remove it is better by now, do you agree?

**Comment by cristianonicolai** [comment]
@spolti not sure, the only thing is that prs wouldn't be verified? I'm fine how you guys want to handle this, deleting would at least unblock things.

**Review by cristianonicolai — APPROVED** [review]

**Comment by spolti** [comment]
will merge after bump the images to 0.9.0.rc1.

**Pull request merged**
