### PR TITLE
KOGITO-9274 Cekit 4.6+ does not support some module version scheme

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-9274

### CODE REVIEW

**Comment by kie-ci1** [comment]
**PR job** `#718` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/718/display/redirect

**Test results:**
- PASSED: 262
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/718/testReport/features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature//verify_if_of_container_is_correctly_started_with_oracle_parameters/">features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature..verify if of container is correctly started with oracle parameters</a></summary>
Message 'Datasource '<default>': IO Error: The Network Adapter could not establish the connection' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/718/testReport/features.image.kogito-swf-devmode/Serverless Workflow devmode images/Verify_if_container_starts_correctly_when_QUARKUS_EXTENSIONS_env_is_used/">features.image.kogito-swf-devmode.Serverless Workflow devmode images.Verify if container starts correctly when QUARKUS_EXTENSIONS env is used</a></summary>
Regex 'Installed features:.*kubernetes' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/718/testReport/features.image.kogito-swf-builder/Serverless Workflow builder images/Verify_that_the_application_is_built_and_started_correctly/">features.image.kogito-swf-builder.Serverless Workflow builder images.Verify that the application is built and started correctly</a></summary>
Regex 'Installed features:.*kubernetes' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/718/testReport/features.image.kogito-swf-builder/Serverless Workflow builder images/Verify_that_the_application_is_built_and_started_correctly_when_QUARKUS_EXTENSIONS_env_is_used/">features.image.kogito-swf-builder.Serverless Workflow builder images.Verify that the application is built and started correctly when QUARKUS_EXTENSIONS env is used</a></summary>
('handle_request failed', 200)
</details>

**Review by desmax74 — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#719` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/719/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare offline kogito-examples)<br/>Stage "Prepare offline kogito-examples" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Fri Jun  2 09:07:28 EDT 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Fri Jun  2 09:07:28 EDT 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/719/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by spolti** [comment]
there is no need to do it, this version fix will be fixed on cekit 4.8
please wait this release to be ready.

cekit 4.6 and 4.7 has the same issue, it was reported here: https://github.com/cekit/cekit/issues/858

**Review by spolti — APPROVED** [review]

**Pull request merged**
