### PR TITLE
Added support for MAVEN_MIRROR_URL. This allows users to use an envir…

### PR DESCRIPTION
**Pull request by DuncanDoyle**
…onment variable to point the builder to, for example, an internal Maven repository manager.

### CODE REVIEW

**Review by mswiderski — APPROVED** [review]
looks good to me

**Comment by spolti** [comment]
Hey all, please hold this PR, I am on process of migrating the images to CeKit.
Not much is left, and I'll incorporate these changes on the upcoming PR.

**Comment by spolti** [comment]
Changes incorporated on https://github.com/kiegroup/submarine-cloud/pull/10

**Comment by DuncanDoyle** [comment]
@mswiderski @spolti : I guess we can close this one in favour of #10 ..... Now I'm still not a Submarine committer :'(

:p

**Comment by mswiderski** [comment]
@DuncanDoyle you are ... actually the first one https://github.com/kiegroup/submarine-cloud/pull/1

**Comment by DuncanDoyle** [comment]
> @DuncanDoyle you are ... actually the first one #1

Hahahaha, LOL

**Comment by mswiderski** [comment]
closing in favour of the #10

**Pull request closed without merging**
