### PR TITLE
[KOGITO-2543] - Maven downloading process output not turned off for a…

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
…rchetype generation

Jira issue : https://issues.redhat.com/browse/KOGITO-2543

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Review by Kaitou786 — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@spolti we might need this for 0.12

**Comment by radtriste** [comment]
@ricardozanini images have already been tested for 0.12.0. So please we should not add any code ...

**Comment by spolti** [comment]
can be merged after https://github.com/kiegroup/kogito-images/pull/191

**Comment by radtriste** [comment]
@ricardozanini this can be merged

**Pull request merged**
