### PR TITLE
[0.9.x][KOGITO-1948] Updated to 0.9.2-rc1

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-1948

### CODE REVIEW

**Comment by radtriste** [comment]
will updated with new snapshots version once https://github.com/kiegroup/kogito-apps/pull/193 is merged and deployed into snapshot repository

**Review by sutaakar — APPROVED** [review]

**Comment by ricardozanini** [comment]
Are we going to have a `0.9.2`?

**Comment by radtriste** [comment]
not sure, but we should be ready in case :)
I think this should be automatic once we release the previous one

**Comment by spolti** [comment]
@radtriste it should be.For next releases let's do this way.
same PR but different commits.

**Review by spolti — APPROVED** [review]

**Pull request merged**
