### PR TITLE
KOGITO-5536 Changed version names for clarity in pipelines

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by spolti** [comment]
@radtriste is it something that you'll continue to work on?

**Comment by radtriste** [comment]
yes it is ;)

**Comment by radtriste** [comment]
will be implemented as part of https://issues.redhat.com/browse/KOGITO-6273

**Pull request closed without merging**
