### PR TITLE
test

### PR DESCRIPTION
**Pull request by spolti**
test

### CODE REVIEW

**Comment by spolti** [comment]
@sutaakar @ricardozanini @mswiderski 
does it sounds good? let me know what you guys think about it. After https://github.com/kiegroup/kogito-cloud/pull/67 is merged I'll add the remaining tests and cook the final PR.

**Comment by sutaakar** [comment]
Looks good to me.

**Comment by ricardozanini** [comment]
Looks good, but the final version will run every bats inside the project, right? I’ll open a JIRA to migrate to GH Actions from CircleCI in the Operator project as well.

**Review by ricardozanini — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by spolti** [comment]
closing, see https://github.com/kiegroup/kogito-cloud/pull/80

**Pull request closed without merging**
