### PR TITLE
[KOGITO-2005] - Prepare master branch for the next iteration.

### PR DESCRIPTION
**Pull request by spolti**
Prepare master branch for the next iteration.

See https://issues.redhat.com/browse/KOGITO-2005

Signed-off-by: spolti <fspolti@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Review by Kaitou786 — APPROVED** [review]

**Comment by radtriste** [comment]
Just thinking ... Could we have a follow-up image instead ?
Title is confusing as we are setting to the next version and not 0.11.0 ...

**Review by sutaakar — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by Kaitou786 — APPROVED** [review]

**Review by vaibhavjainwiz — COMMENTED** [review]
LGTM

**Review by vaibhavjainwiz — APPROVED** [review]

**Comment by spolti** [comment]
> g to the next version and not 0.11.0 ...

Didn't understand, what do you meant by followup image?
the commit description has a message telling that its purpose is to prepare master branch for the next iteration/version.

**Comment by radtriste** [comment]
@spolti I meant that the title of the PR is confusing regarding its content. We should change the way we are naming those as here, this is not the release but the set to the next version

**Pull request merged**
