### PR TITLE
NO-ISSUE - Fix Service Discovery BDD Test Scenario for SonataFlow devmode and builder.

### PR DESCRIPTION
**Pull request by ricardozanini**
Many thanks for submitting your Pull Request :heart:! 

In this PR, we do a small fix in the feature test to verify if the service discovery add-on is installed. In the previous version, when we used Fabric8 the logs were printing a message failing to find the given service. Now that we are defaulting to the operator svc discovery, we don't have this message in the logs anymore, hence the error.

Relates to #1713 

CI reported the error here: https://ci-builds.apache.org/blue/organizations/jenkins/KIE%2Fkogito%2Fmain%2Fnightly%2Fkogito-images.build-image/detail/kogito-images.build-image/172/pipeline/

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>

- <b>Prod tests</b>  
  Please add comment: <b>Jenkins (re)run [prod|Prod|PROD]</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Review by wmedvede — APPROVED** [review]

**Comment by ricardozanini** [comment]
@jstastny-cz can you shed light on this CI error?

> Index 1 out of bounds for length 1

**Comment by jstastny-cz** [comment]
I officially hate the github branch source plugin, see:

For PR coming from my fork:
`CHANGE_FORK=jstastny-cz/kogito-images`

For PR coming from your fork:
`CHANGE_FORK=ricardozanini`

just because in your case the repository name equals.

That's wonderful for stability :/ 

@rodrigonull @cimbalek if you ever see this in future ;-) I'll add some ifs in the util scripts now.

**Comment by jstastny-cz** [comment]
We need
* apache/incubator-kie-kogito-pipelines#1148  

merged before retriggering.

Also I think this would prevent PR checks from working correctly:
* apache/incubator-kie-issues#751

And fix for that one would re-generate the pipelines.

**Comment by ricardozanini** [comment]
Jenkins retest this

**Comment by kie-ci3** [comment]
**PR job** `#6` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/6/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/ricardozanini/incubator-kie-kogito-images<br/> * branch              no-issue-fix-bdd -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/ricardozanini/incubator-kie-kogito-images no-issue-fix-bdd<br/>        Target: 3f139869 [main] Update version to 2.0.0-snapshot<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/6/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#7` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/7/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-trusty-ui<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-management-console<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-task-console<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-s2i-builder seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/7/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Pull request merged**
