### PR TITLE
Fix kogito apps build with pnpm

### PR DESCRIPTION
**Pull request by radtriste**
Failing due to kogito apps migration to `pnpm` => https://github.com/kiegroup/kogito-apps/pull/1706

### CODE REVIEW

**Review by lampajr — APPROVED** [review]

**Review by rgdoliveira — APPROVED** [review]

**Comment by kie-ci1** [comment]
**PR job** `#978` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/978/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-jobs-service-allinone: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-swf-builder: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-swf-devmode: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-s2i-builder: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/978/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci1** [comment]
**PR job** `#980` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/980/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] parallel<br/>[Pipeline] { (Branch: kogito-management-console)<br/>[Pipeline] stage<br/>[Pipeline] { (Build&Test kogito-management-console)<br/>[Pipeline] build<br/>Scheduling project: KIE » kogito » main » pullrequest » kogito-images.build-image<br/>Starting building: KIE » kogito » main » pullrequest » kogito-images.build-image #1257<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-management-console: https://github.com/kiegroup/kogito-images/pull/1616 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-management-console<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/980/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci1** [comment]
**PR job** `#979` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/979/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-runtime-jvm: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-swf-builder: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-swf-devmode: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-s2i-builder: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/979/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci1** [comment]
**PR job** `#982` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/982/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-swf-builder: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-swf-devmode: https://github.com/kiegroup/kogito-images/pull/1616 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1616 - kogito-s2i-builder: https://github.com/kiegroup/kogito-images/pull/1616 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-s2i-builder seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Clean workspace<br/>[Pipeline] cleanWs<br/>[WS-CLEANUP] Deleting project workspace...<br/>[WS-CLEANUP] Deferred wipeout is used...<br/>[WS-CLEANUP] done<br/>[Pipeline] echo<br/>[INFO] Workspace cleaned<br/>[Pipeline] echo<br/>[INFO] Cleanup Maven artifacts<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.m2/repository<br/>[Pipeline] echo<br/>[INFO] .m2/repository cleaned<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/982/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by radtriste** [comment]
Test failure known in https://issues.redhat.com/browse/KOGITO-9465

**Review by spolti — APPROVED** [review]

**Pull request merged**
