### PR TITLE
[1.13.x] Remove native checks

### PR DESCRIPTION
**Pull request by radtriste**
- https://github.com/kiegroup/kogito-pipelines/pull/397
- https://github.com/kiegroup/kogito-runtimes/pull/2062
- https://github.com/kiegroup/optaplanner/pull/1866
- https://github.com/kiegroup/optaplanner-quickstarts/pull/300
- https://github.com/kiegroup/kogito-examples/pull/1160
- https://github.com/kiegroup/kogito-images/pull/1155

### CODE REVIEW

**Comment by kie-ci1** [comment]
**PR job** `#20` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 36
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/20/testReport/TESTS-features.image.kogito-builder/xml/[failed_to_read]/">TESTS-features.image.kogito-builder.xml.[failed-to-read]</a></summary>
Failed to read test report file /home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-images/workspaces/kogito-builder/target/test/results/TESTS-features.image.kogito-builder.xml<br/>org.dom4j.DocumentException: Error on line 196 of document  : An invalid XML character (Unicode: 0x1b) was found in the CDATA section.<br/>	at org.dom4j.io.SAXReader.read(SAXReader.java:511)<br/>	at org.dom4j.io.SAXReader.read(SAXReader.java:392)<br/>	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:177)<br/>	at hudson.tasks.junit.TestResult.parse(TestResult.java:378)<br/>	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:308)<br/>	at hudson.tasks.junit.TestResult.parse(TestResult.java:224)<br/>	at hudson.tasks.junit.TestResult.parse(TestResult.java:196)<br/>	at hudson.tasks.junit.TestResult.<init>(TestResult.java:151)<br/>	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:146)<br/>	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:376)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>	at java.lang.Thread.run(Thread.java:750)<br/>Caused by: org.xml.sax.SAXParseException; lineNumber: 196; columnNumber: 54; An invalid XML character (Unicode: 0x1b) was found in the CDATA section.<br/>	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)<br/>	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:399)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:326)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1466)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(XMLDocumentFragmentScannerImpl.java:1689)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3013)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:601)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:111)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)<br/>	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)<br/>	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)<br/>	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:140)<br/>	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1212)<br/>	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)<br/>	at org.dom4j.io.SAXReader.read(SAXReader.java:494)<br/>	... 17 more<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/20/display/redirect

**Comment by radtriste** [comment]
usual test failure with serverless

**Comment by kie-ci1** [comment]
**PR job** `#28` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 36
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/28/testReport/TESTS-features.image.kogito-builder/xml/[failed_to_read]/">TESTS-features.image.kogito-builder.xml.[failed-to-read]</a></summary>
Failed to read test report file /home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-images/workspaces/kogito-builder/target/test/results/TESTS-features.image.kogito-builder.xml<br/>org.dom4j.DocumentException: Error on line 196 of document  : An invalid XML character (Unicode: 0x1b) was found in the CDATA section.<br/>	at org.dom4j.io.SAXReader.read(SAXReader.java:511)<br/>	at org.dom4j.io.SAXReader.read(SAXReader.java:392)<br/>	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:177)<br/>	at hudson.tasks.junit.TestResult.parse(TestResult.java:378)<br/>	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:308)<br/>	at hudson.tasks.junit.TestResult.parse(TestResult.java:224)<br/>	at hudson.tasks.junit.TestResult.parse(TestResult.java:196)<br/>	at hudson.tasks.junit.TestResult.<init>(TestResult.java:151)<br/>	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:146)<br/>	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:376)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>	at java.lang.Thread.run(Thread.java:750)<br/>Caused by: org.xml.sax.SAXParseException; lineNumber: 196; columnNumber: 54; An invalid XML character (Unicode: 0x1b) was found in the CDATA section.<br/>	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)<br/>	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:399)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:326)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1466)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(XMLDocumentFragmentScannerImpl.java:1689)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3013)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:601)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:111)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)<br/>	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)<br/>	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)<br/>	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:140)<br/>	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1212)<br/>	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)<br/>	at org.dom4j.io.SAXReader.read(SAXReader.java:494)<br/>	... 17 more<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/28/display/redirect

**Comment by kie-ci1** [comment]
**PR job** `#29` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/29/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare offline kogito-examples)<br/>Stage "Prepare offline kogito-examples" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Fri Mar  4 09:32:09 EST 2022<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Fri Mar  4 09:32:10 EST 2022<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/29/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci1** [comment]
**PR job** `#30` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 36
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/30/testReport/TESTS-features.image.kogito-builder/xml/[failed_to_read]/">TESTS-features.image.kogito-builder.xml.[failed-to-read]</a></summary>
Failed to read test report file /home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-images/workspaces/kogito-builder/target/test/results/TESTS-features.image.kogito-builder.xml<br/>org.dom4j.DocumentException: Error on line 196 of document  : An invalid XML character (Unicode: 0x1b) was found in the CDATA section.<br/>	at org.dom4j.io.SAXReader.read(SAXReader.java:511)<br/>	at org.dom4j.io.SAXReader.read(SAXReader.java:392)<br/>	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:177)<br/>	at hudson.tasks.junit.TestResult.parse(TestResult.java:378)<br/>	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:308)<br/>	at hudson.tasks.junit.TestResult.parse(TestResult.java:224)<br/>	at hudson.tasks.junit.TestResult.parse(TestResult.java:196)<br/>	at hudson.tasks.junit.TestResult.<init>(TestResult.java:151)<br/>	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:146)<br/>	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:376)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>	at java.lang.Thread.run(Thread.java:750)<br/>Caused by: org.xml.sax.SAXParseException; lineNumber: 196; columnNumber: 54; An invalid XML character (Unicode: 0x1b) was found in the CDATA section.<br/>	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)<br/>	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:399)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:326)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1466)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(XMLDocumentFragmentScannerImpl.java:1689)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3013)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:601)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:111)<br/>	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)<br/>	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)<br/>	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)<br/>	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:140)<br/>	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1212)<br/>	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)<br/>	at org.dom4j.io.SAXReader.read(SAXReader.java:494)<br/>	... 17 more<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/30/display/redirect

**Comment by spolti** [comment]
serverless test issue
 Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateSources threw an exception: org.kie.kogito.codegen.process.ProcessParsingException: Could not parse file /tmp/src/src/main/resources/order-workflow.sw.yaml

**Pull request merged**
