### PR TITLE
Quarkus LTS Upgrade to 3.8.4

### PR DESCRIPTION
**Pull request by porcelli**
Related https://github.com/apache/incubator-kie-issues/issues/958

Ensemble:
https://github.com/apache/incubator-kie-drools/pull/5853
https://github.com/apache/incubator-kie-optaplanner/pull/3076/files
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3477
https://github.com/apache/incubator-kie-kogito-apps/pull/2039
https://github.com/apache/incubator-kie-kogito-examples/pull/1908
https://github.com/apache/incubator-kie-kogito-images/pull/1760

### CODE REVIEW

**Review by ricardozanini — COMMENTED** [review]
@porcelli have you run `update-repository.py`?

**Comment by kie-ci3** [comment]
**PR job** `#156` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/156/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Failed in branch kogito-task-console<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/156/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by porcelli** [comment]
@ricardozanini nope; did manually using grep

**Review by baldimir — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#157` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/157/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: UNSTABLE<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-jobs-service-allinone seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/157/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#158` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/158/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/158/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by ricardozanini — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#160` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/160/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/porcelli/incubator-kie-kogito-images<br/> * branch              quarkus-384 -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/porcelli/incubator-kie-kogito-images quarkus-384<br/>        Target: 2731f446 [kie-issues#963] Remove all references to kogito-task-console and kogito-management-console (#1753)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/160/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#161` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/161/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/porcelli/incubator-kie-kogito-images<br/> * branch              quarkus-384 -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/porcelli/incubator-kie-kogito-images quarkus-384<br/>        Target: 2731f446 [kie-issues#963] Remove all references to kogito-task-console and kogito-management-console (#1753)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/161/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#162` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/162/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/porcelli/incubator-kie-kogito-images<br/> * branch              quarkus-384 -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/porcelli/incubator-kie-kogito-images quarkus-384<br/>        Target: 2731f446 [kie-issues#963] Remove all references to kogito-task-console and kogito-management-console (#1753)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/162/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#163` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/163/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/163/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Review by yesamer — APPROVED** [review]

**Review by pefernan — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#164` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/164/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-devmode: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: FAILURE<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-swf-devmode<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-postgresql: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jit-runner: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-data-index-ephemeral: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-jobs-service-allinone: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Build KIE » kogito » main » pullrequest » kogito-images.build-image PR #1760 - kogito-swf-builder: https://github.com/apache/incubator-kie-kogito-images/pull/1760 completed: SUCCESS<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/164/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Pull request merged**
