### PR TITLE
[RHPAM-4143] - Exclude memory-limit.sh for non-native ocp image build

### PR DESCRIPTION
**Pull request by levivic**
Cherry-pick https://github.com/kiegroup/kogito-images/pull/1059/commits/c67e00e1fde8c5797564c1c3b5afcbedce397c96 to main branch

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins test this

**Comment by kie-ci1** [comment]
**PR job** #192 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 234
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/192/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/192/display/redirect

**Review by spolti — APPROVED** [review]

**Comment by radtriste** [comment]
@ricardozanini could you have a look to the test error in the PR check ?
https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fmain%2Fpullrequest%2Fkogito-images/detail/kogito-images/192/tests

**Comment by ricardozanini** [comment]
> @ricardozanini could you have a look to the test error in the PR check ? https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fmain%2Fpullrequest%2Fkogito-images/detail/kogito-images/192/tests

Looks like the SNAPSHOT is an old version of the SW parser. We've changed that a couple of days ago:

```
ERROR:root:I0131 15:37:03.304490    3512 sti.go:711] [ERROR] Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "subFlowRef" (class io.serverlessworkflow.api.actions.Action), not marked as ignorable (5 known properties: "actionDataFilter", "eventRef", "name", "timeout", "functionRef"])
```

The change:
https://github.com/kiegroup/kogito-examples/commit/06344dbf88f93c838236113fb7419f1fab54d43d#diff-786c3c84c113b9d05a4f37ba950f2a90e4dd388247b77aa85ea2cad98b59fb3aR24

Can we refresh these dependencies?

**Comment by ricardozanini** [comment]
For one moment, my heart stopped. I thought that this was a cherry-pick in another branch. But, since it's in main, it should work.

**Comment by radtriste** [comment]
well.. this is nexus handling ...

**Comment by radtriste** [comment]
I guess this PR can be merged. test failure is not related ... @spolti

**Pull request merged**
