### PR TITLE
[7.13.x] Remove process testing

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by kie-ci1** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 38
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/1/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/1/testReport/features.image.kogito-common-builder-jvm/kogito-builder image JVM build tests/Verify_if_the_s2i_build_is_finished_as_expected_with_debug_enabled/">features.image.kogito-common-builder-jvm.kogito-builder image JVM build tests.Verify if the s2i build is finished as expected with debug enabled</a></summary>
Message 'Started DemoApplication' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/1/testReport/features.image.kogito-common-builder-jvm/kogito-builder image JVM build tests/Verify_if_the_s2i_build_is_finished_as_expected_with_no_runtime_image_and_debug_enabled/">features.image.kogito-common-builder-jvm.kogito-builder image JVM build tests.Verify if the s2i build is finished as expected with no runtime image and debug enabled</a></summary>
Message 'Started DemoApplication' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/1/testReport/features.image.kogito-common-builder-jvm/kogito-builder image JVM build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_multi_module_build_with_debug_enabled/">features.image.kogito-common-builder-jvm.kogito-builder image JVM build tests.Verify if the s2i build is finished as expected using multi-module build with debug enabled</a></summary>
Message 'Started DemoApplication' was not found in the logs
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/1/display/redirect

**Comment by kie-ci1** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 38
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/2/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/2/testReport/features.image.kogito-common-builder-jvm/kogito-builder image JVM build tests/Verify_if_the_s2i_build_is_finished_as_expected_with_debug_enabled/">features.image.kogito-common-builder-jvm.kogito-builder image JVM build tests.Verify if the s2i build is finished as expected with debug enabled</a></summary>
Message 'Started DemoApplication' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/2/testReport/features.image.kogito-common-builder-jvm/kogito-builder image JVM build tests/Verify_if_the_s2i_build_is_finished_as_expected_with_no_runtime_image_and_debug_enabled/">features.image.kogito-common-builder-jvm.kogito-builder image JVM build tests.Verify if the s2i build is finished as expected with no runtime image and debug enabled</a></summary>
Message 'Started DemoApplication' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/2/testReport/features.image.kogito-common-builder-jvm/kogito-builder image JVM build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_multi_module_build_with_debug_enabled/">features.image.kogito-common-builder-jvm.kogito-builder image JVM build tests.Verify if the s2i build is finished as expected using multi-module build with debug enabled</a></summary>
Message 'Started DemoApplication' was not found in the logs
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/2/display/redirect

**Comment by kie-ci1** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 41
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/3/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/3/display/redirect

**Comment by kie-ci1** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 41
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/4/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/4/display/redirect

**Comment by kie-ci1** [comment]
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 41
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/5/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/5/display/redirect

**Comment by kie-ci1** [comment]
**PR job** `#6` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 41
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/6/testReport/features.image.kogito-builder/kogito-builder image tests/Verify_that_the_Kogito_Quarkus_Serverless_Workflow_Extension_is_building_the_service_properly/">features.image.kogito-builder.kogito-builder image tests.Verify that the Kogito Quarkus Serverless Workflow Extension is building the service properly</a></summary>
S2I build failed, check logs!
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/kogito-images/6/display/redirect

**Review by davidesalerno — APPROVED** [review]

**Comment by radtriste** [comment]
swf test failure is expected due

**Pull request merged**
