### PR TITLE
[KOGITO-5088] - Upgrade GraalVM to 21.x on Kogito Images

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: spolti <fspolti@redhat.com>
See: https://issues.redhat.com/browse/KOGITO-5088

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
could we setup a script to update that ?
I mean it would be great then, once the script is ready, to be able to launch it when update of Quarkus is done :)

**Comment by spolti** [comment]
hmm, maybe? are you planning have this script to update only minor versions or major as well (in this case creating  the new module, etc.) ?

**Comment by radtriste** [comment]
this should update the whole version to the one supported by Quarkus, so I guess whole module...
Wouldn't there be a way to just update the module with a placeholder ?

**Comment by spolti** [comment]
yes, we can, we just need to keep in mind when updating to a major version needs to create a new module instead update the existing one, it should be something easy though.
Let's create a jira for it :)

**Pull request merged**
