### PR TITLE
[KOGITO-3463] Corrected clone-repo.sh

### PR DESCRIPTION
**Pull request by radtriste**
if no settings.xml existing

Following https://github.com/kiegroup/kogito-images/pull/246

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by Kaitou786 — APPROVED** [review]
Missed this,
Thanks @radtriste  :)

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
@Kaitou786 CI failing `cat: /home/jenkins/.m2/settings.xml: No such file or directory`

**Comment by Kaitou786** [comment]
> @Kaitou786 CI failing `cat: /home/jenkins/.m2/settings.xml: No such file or directory`

Just checked, the `CI` env var for executing those steps(copying of ~/.m2/settings.xml) is set in Jenkinsfile after #246 , you would need to manual rebase to update your branch specific Jenkinsfile and solve this :)

**Comment by radtriste** [comment]
@Kaitou786 did not get it ... CI env is there in Jenkinsfile => https://github.com/kiegroup/kogito-images/blob/c10e6d480b12b9954aeee3f36174974d4791ec1a/Jenkinsfile#L25

**Comment by Kaitou786** [comment]
> @Kaitou786 did not get it ... CI env is there in Jenkinsfile =>
> 
> https://github.com/kiegroup/kogito-images/blob/c10e6d480b12b9954aeee3f36174974d4791ec1a/Jenkinsfile#L25

@radtriste Yes, it is there for this PR, I was talking about the PR's which were failing with `cat: /home/jenkins/.m2/settings.xml: No such file or directory` the #244 and #245

**Comment by radtriste** [comment]
https://github.com/kiegroup/kogito-images/pull/250

**Pull request closed without merging**
