### PR TITLE
[KOGITO-728] - Bump Kogito images version to 0.7.0-rc1

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Review by ricardozanini — CHANGES_REQUESTED** [review]
Have you changed the behave test as well?

**Comment by spolti** [comment]
Actually I forgot to update the jobs-service and data-index to snapshot.

**Comment by spolti** [comment]
about behave tests we keep using a stable branch of kogito examples, at this moment 0.6.1.

**Comment by spolti** [comment]
@ricardozanini can you please take a look?
need to merge  this one before other PRs on master.

**Review by ricardozanini — APPROVED** [review]
/LGTM 
I guess would be be better if we create a `bump-version.sh` script =D

**Comment by spolti** [comment]
It is on my TODO list, will do this on the pythoin script we create to push the images.

**Pull request merged**
