### PR TITLE
[KOGITO-4222] Use registry creds for img visibility

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-4222

Depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/139
Follow-up on https://github.com/kiegroup/kogito-images/pull/327

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
tested ok 
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/tradisso/job/kogito-4222/job/kogito-images-promote/3/console
- retry is done if failing (happens with access token when push which needs first to create the image, somehow it was failing)
- visibility is correctly set

**Review by sutaakar — APPROVED** [review]

**Comment by Kaitou786** [comment]
I see in deploy we are using docker in functions and in promote pipeline I see podman which is understandable, but do you think in all those function like pushImage and other have a parameter for containerRuntime, which can be default to docker in deploy and podman in promote part
@radtriste any thoughts?

**Comment by radtriste** [comment]
that could be an idea. I will put the container engine as an env.

**Review by Kaitou786 — APPROVED** [review]

**Comment by radtriste** [comment]
Some problems in the testing. Need to check tomorrow

**Review by spolti — APPROVED** [review]

**Comment by radtriste** [comment]
@Kaitou786 Can you double check the last change ?
With env var in DSL definition, it solves the issue of empty env var defined in Jenkinsfile ...

**Review by Kaitou786 — APPROVED** [review]

**Pull request merged**
