### PR TITLE
[0.17.x] [KOGITO-3643] Setup 0.17.0-SNAPSHOT version

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-3643

Done to have nightly which won't conflict with `master` until 0.17.0 is released

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
failing test is a known bug and should be ignored by https://github.com/kiegroup/kogito-images/pull/262

**Comment by spolti** [comment]
@radtriste please rebase.

**Comment by radtriste** [comment]
@spolti https://github.com/kiegroup/kogito-images/pull/262 is for master. need cherry-pick from @Kaitou786

**Review by sutaakar — APPROVED** [review]

**Comment by radtriste** [comment]
@spolti I rebased to be merged once tests are ok

**Review by spolti — APPROVED** [review]

**Review by Kaitou786 — APPROVED** [review]

**Pull request merged**
