### PR TITLE
KOGITO-4306 - Fix update-maven-artifacts for jit runner

### PR DESCRIPTION
**Pull request by r00ta**
JIRA: https://issues.redhat.com/browse/KOGITO-4306

Aims to fix update-maven-artifact script for the new service jit-runner

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by radtriste — CHANGES_REQUESTED** [review]
quick search in repo, you also need to change the name from `kogito-jit-dmn` to `kogito-jit-runner` in `common.py` scripts

**Comment by r00ta** [comment]
> quick search in repo, you also need to change the name from `kogito-jit-dmn` to `kogito-jit-runner` in `common.py` scripts

Good catch! Thanks :+1:

**Review by radtriste — APPROVED** [review]

**Comment by Kaitou786** [comment]
Just a optional nitpick, do we rename the file `kogito-jit-dmn.feature` to `kogito-jit-runner.feature`  as well?

**Review by Kaitou786 — APPROVED** [review]

**Pull request merged**
