### PR TITLE
move from submarine to kogito

### PR DESCRIPTION
**Pull request by mswiderski**
requires to merge all at once
https://github.com/kiegroup/submarine-bom/pull/21
https://github.com/kiegroup/submarine-runtimes/pull/54
https://github.com/kiegroup/submarine-cloud/pull/14
https://github.com/kiegroup/submarine-examples/pull/25

### CODE REVIEW

**Comment by mswiderski** [comment]
@spolti could you please verify the s2i changes and maybe give it a test run with cekit build?

**Comment by spolti** [comment]
@mswiderski sure, shall we merge this before?

**Comment by mswiderski** [comment]
as soon as it is approved :)

**Review by spolti — APPROVED** [review]
the image changes looks good.

**Pull request merged**
