### PR TITLE
[KOGITO-771] - Upgrade GraalVM to 19.3.1

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Review by radtriste — APPROVED** [review]
lgtm

**Review by sutaakar — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by spolti** [comment]
once the jenkins job gets finished I'll push the rc2 tag.

**Comment by spolti** [comment]
Images available under tag rc2
@sutaakar @radtriste please test it.

**Review by evacchi — APPROVED** [review]

**Comment by radtriste** [comment]
Started BDD tests with rc2

**Comment by radtriste** [comment]
tests ran ok with rc2 images

Solved:
- native (with update to Graalvm 19.3.1) => OK
- persistence (https://github.com/kiegroup/kogito-runtimes/pull/346) => OK

**Comment by spolti** [comment]
@radtriste cool, thanks.

**Pull request merged**
