### PR TITLE
NO-ISSUE: drop scripts/logic folder as it is deprecated

### PR DESCRIPTION
**Pull request by rgdoliveira**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#56` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/56/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:623)<br/>	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:852)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:158)<br/>	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:151)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:377)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to builds29<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1000)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)<br/>		at jdk.internal.reflect.GeneratedMethodAccessor1498.invoke(Unknown Source)<br/>		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>		at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:129)<br/>		at com.sun.proxy.$Proxy228.execute(Unknown Source)<br/>		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1226)<br/>		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1309)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)<br/>		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)<br/>		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>		at java.base/java.lang.Thread.run(Thread.java:829)<br/>[Pipeline] deleteDir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/56/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by ricardozanini** [comment]
@rgdoliveira can you please rename your fork to: `repository 'https://github.com/rgdoliveira/incubator-kie-kogito-images.git/' not found`

We currently have an issue in this pipeline here: #1729

**Comment by rgdoliveira** [comment]
ok, thanks for letting me know, I just renamed it

**Comment by ricardozanini** [comment]
Can you sen a force push to refresh the CI? 😬

**Comment by kie-ci3** [comment]
**PR job** `#58` was: **ABORTED**
Possible explanation: Most probably a timeout, please review

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/58/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
08:24:33 INFO Trying to validate file kogito-swf-devmode-image.yaml as [Lorg.kie.cekit.image.descriptors.image.Image;<br/>08:24:33 INFO File multi images [kogito-swf-devmode-image.yaml] loaded and validated<br/>[Pipeline] sh<br/>+ ./cekit-image-validator-runner kogito-task-console-image.yaml<br/>__  ____  __  _____   ___  __ ____  ______ <br/> --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ <br/> -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   <br/>--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   <br/>08:24:37 INFO Provided param is a regular file, analyzing it...<br/>08:24:37 INFO Trying to validate file kogito-task-console-image.yaml<br/>08:24:37 INFO Trying to validate file kogito-task-console-image.yaml as org.kie.cekit.image.descriptors.image.Image<br/>08:24:37 INFO File image [kogito-task-console-image.yaml] loaded and validated<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>Running in /home/jenkins/jenkins-agent/workspace/KIE/kogito/main/pullrequest/kogito-images.build-and-test/incubator-kie-kogito-images<br/>[Pipeline] {<br/>[Pipeline] dir<br/>Running in /home/jenkins/jenkins-agent/workspace/KIE/kogito/main/pullrequest/kogito-images.build-and-test/incubator-kie-kogito-images/githubscm-prepare-commit-incubator-kie-kogito-images<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[INFO] Resolving Repository https://github.com/rgdoliveira/incubator-kie-kogito-images:logic_folder. CredentialsID: 399061d0-5ab5-4142-a186-a52081fef742<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>Aborted by Roberto Oliveira<br/>[Pipeline] deleteDir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/58/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by rgdoliveira** [comment]
@ricardozanini I rerun the PR job via Jenkins UI in https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images-pr/view/change-requests/job/PR-1733/

It is running again

**Comment by kie-ci3** [comment]
**PR job** `#59` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/59/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>Failed in branch kogito-s2i-builder<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/59/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#60` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/60/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-devmode seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/60/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#62` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/62/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/rgdoliveira/incubator-kie-kogito-images<br/> * branch              logic_folder -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/rgdoliveira/incubator-kie-kogito-images logic_folder<br/>        Target: feebea2e [NO-ISSUE] Remove MongoDB leftovers duo to ASF restrictions (#1732)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/62/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#64` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/64/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
From https://github.com/rgdoliveira/incubator-kie-kogito-images<br/> * branch              logic_folder -> FETCH_HEAD<br/>hint: You have divergent branches and need to specify how to reconcile them.<br/>hint: You can do so by running one of the following commands sometime before<br/>hint: your next pull:<br/>hint: <br/>hint:   git config pull.rebase false  # merge (the default strategy)<br/>hint:   git config pull.rebase true   # rebase<br/>hint:   git config pull.ff only       # fast-forward only<br/>hint: <br/>hint: You can replace "git config" with "git config --global" to set a default<br/>hint: preference for all repositories. You can also pass --rebase, --no-rebase,<br/>hint: or --ff-only on the command line to override the configured default per<br/>hint: invocation.<br/>fatal: Need to specify how to reconcile divergent branches.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] echo<br/><br/>        -------------------------------------------------------------<br/>        [ERROR] Can't merge source into Target. Please rebase PR branch.<br/>        -------------------------------------------------------------<br/>        Source: git://github.com/rgdoliveira/incubator-kie-kogito-images logic_folder<br/>        Target: feebea2e [NO-ISSUE] Remove MongoDB leftovers duo to ASF restrictions (#1732)<br/>        -------------------------------------------------------------<br/>        <br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Validate CeKit Image and Modules descriptors)<br/>Stage "Validate CeKit Image and Modules descriptors" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/64/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by rgdoliveira** [comment]
I just rebased this PR as the test was complaining with error message `[ERROR] Can't merge source into Target. Please rebase PR branch.`

Fingers crossed the tests will pass this time.

**Comment by kie-ci3** [comment]
**PR job** `#65` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/65/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] unstable<br/>WARNING: Tests on kogito-swf-devmode seems to have failed<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] }<br/>[Pipeline] // parallel<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/65/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by rgdoliveira** [comment]
merging it as CI is green.

**Pull request merged**
