### PR TITLE
Try to stabilize images build

### PR DESCRIPTION
**Pull request by radtriste**
This should correct a small instability introduced by https://github.com/kiegroup/kogito-images/pull/1206

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#352` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 237
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/352/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_runtime_jvm___Build/Test_kogito_runtime_jvm___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-runtime-jvm / Build/Test kogito-runtime-jvm / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/352/display/redirect

**Comment by radtriste** [comment]
test failure not related. Build is happening well ... relaunching

jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by kie-ci1** [comment]
**PR job** `#355` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 237
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/355/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_jit_runner___Build/Test_kogito_jit_runner___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-jit-runner / Build/Test kogito-jit-runner / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
HOOK-ERROR in after_scenario: APIError: 500 Server Error for http+docker://localhost/v1.22/containers/d80a7d1bef3affe85be42b73f5a0ce36e51b335e83d947f3861b7316329df404/kill: Internal Server Error ("b'Cannot kill container: d80a7d1bef3affe85be42b73f5a0ce36e51b335e83d947f3861b7316329df404: container d80a7d1bef3a PID 28800 is zombie and can not be killed. Use the --init option when creating containers to run an init inside the container that forwards signals and reaps processes'")
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/355/display/redirect

**Comment by radtriste** [comment]
Instability on test due to jenkins. Build is still good.
Retesting...

jenkins retest this

**Comment by radtriste** [comment]
@davidesalerno as @spolti is on PTO, can you please check and approve this PR ?
Build seems more stable
The test failures mentioned in comments are coming from Jenkins infra instabilities ...

**Review by davidesalerno — APPROVED** [review]
/lgtm

**Pull request merged**
