### PR TITLE
[KOGITO-1260] Added missing distributionmanagement tag

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-1260

### CODE REVIEW

**Review by evacchi — APPROVED** [review]
looks fine, not sure why it's red though

**Comment by radtriste** [comment]
bats tests => there was a problem when init
pr-merge => no test results on s2i build ...

**Review by cristianonicolai — APPROVED** [review]

**Review by mariofusco — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
This https://github.com/kiegroup/kogito-cloud/pull/94 will fix the the github actions failures.

**Comment by spolti** [comment]
@radtriste can you please rebase?

**Comment by radtriste** [comment]
jenkins test

**Comment by radtriste** [comment]
@spolti rebased and GH actions are ok.
there is a problem on jenkins job as it is waiting for junit results for the s2i build. is that normal ?

**Comment by spolti** [comment]
@radtriste to be honest I don't know why that is failing, I'll go ahead and merge it as this failure is not related with your changes then I'll ask someone to take a look on this.

**Pull request merged**
