### PR TITLE
[KOGITO-1250] Removed openshift tests (done in operator)

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-1250

Service discovery on Openshift is now tested on Operator BDD tests: https://issues.redhat.com/browse/KOGITO-997

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Comment by spolti** [comment]
looks good, however CI is complianing:

```Child module /home/jenkins/workspace/KIE_kogito_kogito-cloud_PR-92/kogito-cloud-tests of /home/jenkins/workspace/KIE_kogito_kogito-cloud_PR-92/pom.xml does not exist```

not sure why this happened.

**Comment by radtriste** [comment]
@spolti updated the module part ...
Can you relaunch the tests ? Seems that the bats test has some problem to reach the sources list ...

**Review by MarianMacik — APPROVED** [review]

**Comment by spolti** [comment]
@radtriste to re-trigger the github action do you mind to do a minor change and update the PR? I don't know why but if we try to re-run these, it always fail.

**Comment by spolti** [comment]
@radtriste can you please rebase? Just pushed a fix for the GitHub actions tests.

**Review by ricardozanini — APPROVED** [review]

**Comment by radtriste** [comment]
@spolti same problem here on s2i build

**Review by spolti — APPROVED** [review]

**Pull request merged**
